/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UserImport } from './routes/user'
import { Route as AuthImport } from './routes/auth'
import { Route as AppImport } from './routes/app'
import { Route as AdminImport } from './routes/admin'
import { Route as IndexImport } from './routes/index'
import { Route as UserEmailVerificationImport } from './routes/user.email-verification'
import { Route as UserChangePasswordImport } from './routes/user.change-password'
import { Route as UserChangeEmailImport } from './routes/user.change-email'
import { Route as UserAccountSettingsImport } from './routes/user.account-settings'
import { Route as AuthSignUpImport } from './routes/auth.sign-up'
import { Route as AuthSignInImport } from './routes/auth.sign-in'
import { Route as AppTenantsImport } from './routes/app.tenants'
import { Route as AppPropertiesImport } from './routes/app.properties'
import { Route as AppMaintenanceImport } from './routes/app.maintenance'
import { Route as AppLeasesImport } from './routes/app.leases'
import { Route as AppFinancialsImport } from './routes/app.financials'
import { Route as AppDocumentsImport } from './routes/app.documents'
import { Route as AppDashboardImport } from './routes/app.dashboard'
import { Route as AppCommunicationsImport } from './routes/app.communications'
import { Route as AdminUserManagementImport } from './routes/admin.user-management'
import { Route as AdminDashboardImport } from './routes/admin.dashboard'
import { Route as examplesExampleFormImport } from './routes/(examples)/example-form'
import { Route as AppTenantsIndexImport } from './routes/app.tenants.index'
import { Route as AppPropertiesIndexImport } from './routes/app.properties.index'
import { Route as AppMaintenanceIndexImport } from './routes/app.maintenance.index'
import { Route as AppLeasesIndexImport } from './routes/app.leases.index'
import { Route as AppFinancialsIndexImport } from './routes/app.financials.index'
import { Route as AuthSignUpWelcomeImport } from './routes/auth.sign-up.welcome'
import { Route as AuthSignUpVerifyImport } from './routes/auth.sign-up.verify'
import { Route as AuthSignUpProfileImport } from './routes/auth.sign-up.profile'
import { Route as AppTenantsNewImport } from './routes/app.tenants.new'
import { Route as AppTenantsTenantIdImport } from './routes/app.tenants.$tenantId'
import { Route as AppPropertiesNewImport } from './routes/app.properties.new'
import { Route as AppPropertiesPropertyIdImport } from './routes/app.properties.$propertyId'
import { Route as AppMaintenanceNewImport } from './routes/app.maintenance.new'
import { Route as AppMaintenanceWorkOrderIdImport } from './routes/app.maintenance.$workOrderId'
import { Route as AppLeasesNewImport } from './routes/app.leases.new'
import { Route as AppLeasesLeaseIdImport } from './routes/app.leases.$leaseId'
import { Route as AppFinancialsPaymentsImport } from './routes/app.financials.payments'
import { Route as AppFinancialsExpensesImport } from './routes/app.financials.expenses'
import { Route as AppPropertiesPropertyIdIndexImport } from './routes/app.properties.$propertyId.index'
import { Route as AppPropertiesPropertyIdUnitsImport } from './routes/app.properties.$propertyId.units'

// Create/Update Routes

const UserRoute = UserImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UserEmailVerificationRoute = UserEmailVerificationImport.update({
  id: '/email-verification',
  path: '/email-verification',
  getParentRoute: () => UserRoute,
} as any)

const UserChangePasswordRoute = UserChangePasswordImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => UserRoute,
} as any)

const UserChangeEmailRoute = UserChangeEmailImport.update({
  id: '/change-email',
  path: '/change-email',
  getParentRoute: () => UserRoute,
} as any)

const UserAccountSettingsRoute = UserAccountSettingsImport.update({
  id: '/account-settings',
  path: '/account-settings',
  getParentRoute: () => UserRoute,
} as any)

const AuthSignUpRoute = AuthSignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)

const AuthSignInRoute = AuthSignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)

const AppTenantsRoute = AppTenantsImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AppRoute,
} as any)

const AppPropertiesRoute = AppPropertiesImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AppRoute,
} as any)

const AppMaintenanceRoute = AppMaintenanceImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AppRoute,
} as any)

const AppLeasesRoute = AppLeasesImport.update({
  id: '/leases',
  path: '/leases',
  getParentRoute: () => AppRoute,
} as any)

const AppFinancialsRoute = AppFinancialsImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => AppRoute,
} as any)

const AppDocumentsRoute = AppDocumentsImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)

const AppDashboardRoute = AppDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)

const AppCommunicationsRoute = AppCommunicationsImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => AppRoute,
} as any)

const AdminUserManagementRoute = AdminUserManagementImport.update({
  id: '/user-management',
  path: '/user-management',
  getParentRoute: () => AdminRoute,
} as any)

const AdminDashboardRoute = AdminDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)

const examplesExampleFormRoute = examplesExampleFormImport.update({
  id: '/(examples)/example-form',
  path: '/example-form',
  getParentRoute: () => rootRoute,
} as any)

const AppTenantsIndexRoute = AppTenantsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTenantsRoute,
} as any)

const AppPropertiesIndexRoute = AppPropertiesIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPropertiesRoute,
} as any)

const AppMaintenanceIndexRoute = AppMaintenanceIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMaintenanceRoute,
} as any)

const AppLeasesIndexRoute = AppLeasesIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLeasesRoute,
} as any)

const AppFinancialsIndexRoute = AppFinancialsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFinancialsRoute,
} as any)

const AuthSignUpWelcomeRoute = AuthSignUpWelcomeImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthSignUpRoute,
} as any)

const AuthSignUpVerifyRoute = AuthSignUpVerifyImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthSignUpRoute,
} as any)

const AuthSignUpProfileRoute = AuthSignUpProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthSignUpRoute,
} as any)

const AppTenantsNewRoute = AppTenantsNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppTenantsRoute,
} as any)

const AppTenantsTenantIdRoute = AppTenantsTenantIdImport.update({
  id: '/$tenantId',
  path: '/$tenantId',
  getParentRoute: () => AppTenantsRoute,
} as any)

const AppPropertiesNewRoute = AppPropertiesNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppPropertiesRoute,
} as any)

const AppPropertiesPropertyIdRoute = AppPropertiesPropertyIdImport.update({
  id: '/$propertyId',
  path: '/$propertyId',
  getParentRoute: () => AppPropertiesRoute,
} as any)

const AppMaintenanceNewRoute = AppMaintenanceNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppMaintenanceRoute,
} as any)

const AppMaintenanceWorkOrderIdRoute = AppMaintenanceWorkOrderIdImport.update({
  id: '/$workOrderId',
  path: '/$workOrderId',
  getParentRoute: () => AppMaintenanceRoute,
} as any)

const AppLeasesNewRoute = AppLeasesNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppLeasesRoute,
} as any)

const AppLeasesLeaseIdRoute = AppLeasesLeaseIdImport.update({
  id: '/$leaseId',
  path: '/$leaseId',
  getParentRoute: () => AppLeasesRoute,
} as any)

const AppFinancialsPaymentsRoute = AppFinancialsPaymentsImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppFinancialsRoute,
} as any)

const AppFinancialsExpensesRoute = AppFinancialsExpensesImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppFinancialsRoute,
} as any)

const AppPropertiesPropertyIdIndexRoute =
  AppPropertiesPropertyIdIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppPropertiesPropertyIdRoute,
  } as any)

const AppPropertiesPropertyIdUnitsRoute =
  AppPropertiesPropertyIdUnitsImport.update({
    id: '/units',
    path: '/units',
    getParentRoute: () => AppPropertiesPropertyIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserImport
      parentRoute: typeof rootRoute
    }
    '/(examples)/example-form': {
      id: '/(examples)/example-form'
      path: '/example-form'
      fullPath: '/example-form'
      preLoaderRoute: typeof examplesExampleFormImport
      parentRoute: typeof rootRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardImport
      parentRoute: typeof AdminImport
    }
    '/admin/user-management': {
      id: '/admin/user-management'
      path: '/user-management'
      fullPath: '/admin/user-management'
      preLoaderRoute: typeof AdminUserManagementImport
      parentRoute: typeof AdminImport
    }
    '/app/communications': {
      id: '/app/communications'
      path: '/communications'
      fullPath: '/app/communications'
      preLoaderRoute: typeof AppCommunicationsImport
      parentRoute: typeof AppImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardImport
      parentRoute: typeof AppImport
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsImport
      parentRoute: typeof AppImport
    }
    '/app/financials': {
      id: '/app/financials'
      path: '/financials'
      fullPath: '/app/financials'
      preLoaderRoute: typeof AppFinancialsImport
      parentRoute: typeof AppImport
    }
    '/app/leases': {
      id: '/app/leases'
      path: '/leases'
      fullPath: '/app/leases'
      preLoaderRoute: typeof AppLeasesImport
      parentRoute: typeof AppImport
    }
    '/app/maintenance': {
      id: '/app/maintenance'
      path: '/maintenance'
      fullPath: '/app/maintenance'
      preLoaderRoute: typeof AppMaintenanceImport
      parentRoute: typeof AppImport
    }
    '/app/properties': {
      id: '/app/properties'
      path: '/properties'
      fullPath: '/app/properties'
      preLoaderRoute: typeof AppPropertiesImport
      parentRoute: typeof AppImport
    }
    '/app/tenants': {
      id: '/app/tenants'
      path: '/tenants'
      fullPath: '/app/tenants'
      preLoaderRoute: typeof AppTenantsImport
      parentRoute: typeof AppImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInImport
      parentRoute: typeof AuthImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpImport
      parentRoute: typeof AuthImport
    }
    '/user/account-settings': {
      id: '/user/account-settings'
      path: '/account-settings'
      fullPath: '/user/account-settings'
      preLoaderRoute: typeof UserAccountSettingsImport
      parentRoute: typeof UserImport
    }
    '/user/change-email': {
      id: '/user/change-email'
      path: '/change-email'
      fullPath: '/user/change-email'
      preLoaderRoute: typeof UserChangeEmailImport
      parentRoute: typeof UserImport
    }
    '/user/change-password': {
      id: '/user/change-password'
      path: '/change-password'
      fullPath: '/user/change-password'
      preLoaderRoute: typeof UserChangePasswordImport
      parentRoute: typeof UserImport
    }
    '/user/email-verification': {
      id: '/user/email-verification'
      path: '/email-verification'
      fullPath: '/user/email-verification'
      preLoaderRoute: typeof UserEmailVerificationImport
      parentRoute: typeof UserImport
    }
    '/app/financials/expenses': {
      id: '/app/financials/expenses'
      path: '/expenses'
      fullPath: '/app/financials/expenses'
      preLoaderRoute: typeof AppFinancialsExpensesImport
      parentRoute: typeof AppFinancialsImport
    }
    '/app/financials/payments': {
      id: '/app/financials/payments'
      path: '/payments'
      fullPath: '/app/financials/payments'
      preLoaderRoute: typeof AppFinancialsPaymentsImport
      parentRoute: typeof AppFinancialsImport
    }
    '/app/leases/$leaseId': {
      id: '/app/leases/$leaseId'
      path: '/$leaseId'
      fullPath: '/app/leases/$leaseId'
      preLoaderRoute: typeof AppLeasesLeaseIdImport
      parentRoute: typeof AppLeasesImport
    }
    '/app/leases/new': {
      id: '/app/leases/new'
      path: '/new'
      fullPath: '/app/leases/new'
      preLoaderRoute: typeof AppLeasesNewImport
      parentRoute: typeof AppLeasesImport
    }
    '/app/maintenance/$workOrderId': {
      id: '/app/maintenance/$workOrderId'
      path: '/$workOrderId'
      fullPath: '/app/maintenance/$workOrderId'
      preLoaderRoute: typeof AppMaintenanceWorkOrderIdImport
      parentRoute: typeof AppMaintenanceImport
    }
    '/app/maintenance/new': {
      id: '/app/maintenance/new'
      path: '/new'
      fullPath: '/app/maintenance/new'
      preLoaderRoute: typeof AppMaintenanceNewImport
      parentRoute: typeof AppMaintenanceImport
    }
    '/app/properties/$propertyId': {
      id: '/app/properties/$propertyId'
      path: '/$propertyId'
      fullPath: '/app/properties/$propertyId'
      preLoaderRoute: typeof AppPropertiesPropertyIdImport
      parentRoute: typeof AppPropertiesImport
    }
    '/app/properties/new': {
      id: '/app/properties/new'
      path: '/new'
      fullPath: '/app/properties/new'
      preLoaderRoute: typeof AppPropertiesNewImport
      parentRoute: typeof AppPropertiesImport
    }
    '/app/tenants/$tenantId': {
      id: '/app/tenants/$tenantId'
      path: '/$tenantId'
      fullPath: '/app/tenants/$tenantId'
      preLoaderRoute: typeof AppTenantsTenantIdImport
      parentRoute: typeof AppTenantsImport
    }
    '/app/tenants/new': {
      id: '/app/tenants/new'
      path: '/new'
      fullPath: '/app/tenants/new'
      preLoaderRoute: typeof AppTenantsNewImport
      parentRoute: typeof AppTenantsImport
    }
    '/auth/sign-up/profile': {
      id: '/auth/sign-up/profile'
      path: '/profile'
      fullPath: '/auth/sign-up/profile'
      preLoaderRoute: typeof AuthSignUpProfileImport
      parentRoute: typeof AuthSignUpImport
    }
    '/auth/sign-up/verify': {
      id: '/auth/sign-up/verify'
      path: '/verify'
      fullPath: '/auth/sign-up/verify'
      preLoaderRoute: typeof AuthSignUpVerifyImport
      parentRoute: typeof AuthSignUpImport
    }
    '/auth/sign-up/welcome': {
      id: '/auth/sign-up/welcome'
      path: '/welcome'
      fullPath: '/auth/sign-up/welcome'
      preLoaderRoute: typeof AuthSignUpWelcomeImport
      parentRoute: typeof AuthSignUpImport
    }
    '/app/financials/': {
      id: '/app/financials/'
      path: '/'
      fullPath: '/app/financials/'
      preLoaderRoute: typeof AppFinancialsIndexImport
      parentRoute: typeof AppFinancialsImport
    }
    '/app/leases/': {
      id: '/app/leases/'
      path: '/'
      fullPath: '/app/leases/'
      preLoaderRoute: typeof AppLeasesIndexImport
      parentRoute: typeof AppLeasesImport
    }
    '/app/maintenance/': {
      id: '/app/maintenance/'
      path: '/'
      fullPath: '/app/maintenance/'
      preLoaderRoute: typeof AppMaintenanceIndexImport
      parentRoute: typeof AppMaintenanceImport
    }
    '/app/properties/': {
      id: '/app/properties/'
      path: '/'
      fullPath: '/app/properties/'
      preLoaderRoute: typeof AppPropertiesIndexImport
      parentRoute: typeof AppPropertiesImport
    }
    '/app/tenants/': {
      id: '/app/tenants/'
      path: '/'
      fullPath: '/app/tenants/'
      preLoaderRoute: typeof AppTenantsIndexImport
      parentRoute: typeof AppTenantsImport
    }
    '/app/properties/$propertyId/units': {
      id: '/app/properties/$propertyId/units'
      path: '/units'
      fullPath: '/app/properties/$propertyId/units'
      preLoaderRoute: typeof AppPropertiesPropertyIdUnitsImport
      parentRoute: typeof AppPropertiesPropertyIdImport
    }
    '/app/properties/$propertyId/': {
      id: '/app/properties/$propertyId/'
      path: '/'
      fullPath: '/app/properties/$propertyId/'
      preLoaderRoute: typeof AppPropertiesPropertyIdIndexImport
      parentRoute: typeof AppPropertiesPropertyIdImport
    }
  }
}

// Create and export the route tree

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminUserManagementRoute: typeof AdminUserManagementRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminUserManagementRoute: AdminUserManagementRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppFinancialsRouteChildren {
  AppFinancialsExpensesRoute: typeof AppFinancialsExpensesRoute
  AppFinancialsPaymentsRoute: typeof AppFinancialsPaymentsRoute
  AppFinancialsIndexRoute: typeof AppFinancialsIndexRoute
}

const AppFinancialsRouteChildren: AppFinancialsRouteChildren = {
  AppFinancialsExpensesRoute: AppFinancialsExpensesRoute,
  AppFinancialsPaymentsRoute: AppFinancialsPaymentsRoute,
  AppFinancialsIndexRoute: AppFinancialsIndexRoute,
}

const AppFinancialsRouteWithChildren = AppFinancialsRoute._addFileChildren(
  AppFinancialsRouteChildren,
)

interface AppLeasesRouteChildren {
  AppLeasesLeaseIdRoute: typeof AppLeasesLeaseIdRoute
  AppLeasesNewRoute: typeof AppLeasesNewRoute
  AppLeasesIndexRoute: typeof AppLeasesIndexRoute
}

const AppLeasesRouteChildren: AppLeasesRouteChildren = {
  AppLeasesLeaseIdRoute: AppLeasesLeaseIdRoute,
  AppLeasesNewRoute: AppLeasesNewRoute,
  AppLeasesIndexRoute: AppLeasesIndexRoute,
}

const AppLeasesRouteWithChildren = AppLeasesRoute._addFileChildren(
  AppLeasesRouteChildren,
)

interface AppMaintenanceRouteChildren {
  AppMaintenanceWorkOrderIdRoute: typeof AppMaintenanceWorkOrderIdRoute
  AppMaintenanceNewRoute: typeof AppMaintenanceNewRoute
  AppMaintenanceIndexRoute: typeof AppMaintenanceIndexRoute
}

const AppMaintenanceRouteChildren: AppMaintenanceRouteChildren = {
  AppMaintenanceWorkOrderIdRoute: AppMaintenanceWorkOrderIdRoute,
  AppMaintenanceNewRoute: AppMaintenanceNewRoute,
  AppMaintenanceIndexRoute: AppMaintenanceIndexRoute,
}

const AppMaintenanceRouteWithChildren = AppMaintenanceRoute._addFileChildren(
  AppMaintenanceRouteChildren,
)

interface AppPropertiesPropertyIdRouteChildren {
  AppPropertiesPropertyIdUnitsRoute: typeof AppPropertiesPropertyIdUnitsRoute
  AppPropertiesPropertyIdIndexRoute: typeof AppPropertiesPropertyIdIndexRoute
}

const AppPropertiesPropertyIdRouteChildren: AppPropertiesPropertyIdRouteChildren =
  {
    AppPropertiesPropertyIdUnitsRoute: AppPropertiesPropertyIdUnitsRoute,
    AppPropertiesPropertyIdIndexRoute: AppPropertiesPropertyIdIndexRoute,
  }

const AppPropertiesPropertyIdRouteWithChildren =
  AppPropertiesPropertyIdRoute._addFileChildren(
    AppPropertiesPropertyIdRouteChildren,
  )

interface AppPropertiesRouteChildren {
  AppPropertiesPropertyIdRoute: typeof AppPropertiesPropertyIdRouteWithChildren
  AppPropertiesNewRoute: typeof AppPropertiesNewRoute
  AppPropertiesIndexRoute: typeof AppPropertiesIndexRoute
}

const AppPropertiesRouteChildren: AppPropertiesRouteChildren = {
  AppPropertiesPropertyIdRoute: AppPropertiesPropertyIdRouteWithChildren,
  AppPropertiesNewRoute: AppPropertiesNewRoute,
  AppPropertiesIndexRoute: AppPropertiesIndexRoute,
}

const AppPropertiesRouteWithChildren = AppPropertiesRoute._addFileChildren(
  AppPropertiesRouteChildren,
)

interface AppTenantsRouteChildren {
  AppTenantsTenantIdRoute: typeof AppTenantsTenantIdRoute
  AppTenantsNewRoute: typeof AppTenantsNewRoute
  AppTenantsIndexRoute: typeof AppTenantsIndexRoute
}

const AppTenantsRouteChildren: AppTenantsRouteChildren = {
  AppTenantsTenantIdRoute: AppTenantsTenantIdRoute,
  AppTenantsNewRoute: AppTenantsNewRoute,
  AppTenantsIndexRoute: AppTenantsIndexRoute,
}

const AppTenantsRouteWithChildren = AppTenantsRoute._addFileChildren(
  AppTenantsRouteChildren,
)

interface AppRouteChildren {
  AppCommunicationsRoute: typeof AppCommunicationsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppFinancialsRoute: typeof AppFinancialsRouteWithChildren
  AppLeasesRoute: typeof AppLeasesRouteWithChildren
  AppMaintenanceRoute: typeof AppMaintenanceRouteWithChildren
  AppPropertiesRoute: typeof AppPropertiesRouteWithChildren
  AppTenantsRoute: typeof AppTenantsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppCommunicationsRoute: AppCommunicationsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppFinancialsRoute: AppFinancialsRouteWithChildren,
  AppLeasesRoute: AppLeasesRouteWithChildren,
  AppMaintenanceRoute: AppMaintenanceRouteWithChildren,
  AppPropertiesRoute: AppPropertiesRouteWithChildren,
  AppTenantsRoute: AppTenantsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthSignUpRouteChildren {
  AuthSignUpProfileRoute: typeof AuthSignUpProfileRoute
  AuthSignUpVerifyRoute: typeof AuthSignUpVerifyRoute
  AuthSignUpWelcomeRoute: typeof AuthSignUpWelcomeRoute
}

const AuthSignUpRouteChildren: AuthSignUpRouteChildren = {
  AuthSignUpProfileRoute: AuthSignUpProfileRoute,
  AuthSignUpVerifyRoute: AuthSignUpVerifyRoute,
  AuthSignUpWelcomeRoute: AuthSignUpWelcomeRoute,
}

const AuthSignUpRouteWithChildren = AuthSignUpRoute._addFileChildren(
  AuthSignUpRouteChildren,
)

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface UserRouteChildren {
  UserAccountSettingsRoute: typeof UserAccountSettingsRoute
  UserChangeEmailRoute: typeof UserChangeEmailRoute
  UserChangePasswordRoute: typeof UserChangePasswordRoute
  UserEmailVerificationRoute: typeof UserEmailVerificationRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserAccountSettingsRoute: UserAccountSettingsRoute,
  UserChangeEmailRoute: UserChangeEmailRoute,
  UserChangePasswordRoute: UserChangePasswordRoute,
  UserEmailVerificationRoute: UserEmailVerificationRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/example-form': typeof examplesExampleFormRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/user-management': typeof AdminUserManagementRoute
  '/app/communications': typeof AppCommunicationsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/financials': typeof AppFinancialsRouteWithChildren
  '/app/leases': typeof AppLeasesRouteWithChildren
  '/app/maintenance': typeof AppMaintenanceRouteWithChildren
  '/app/properties': typeof AppPropertiesRouteWithChildren
  '/app/tenants': typeof AppTenantsRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRouteWithChildren
  '/user/account-settings': typeof UserAccountSettingsRoute
  '/user/change-email': typeof UserChangeEmailRoute
  '/user/change-password': typeof UserChangePasswordRoute
  '/user/email-verification': typeof UserEmailVerificationRoute
  '/app/financials/expenses': typeof AppFinancialsExpensesRoute
  '/app/financials/payments': typeof AppFinancialsPaymentsRoute
  '/app/leases/$leaseId': typeof AppLeasesLeaseIdRoute
  '/app/leases/new': typeof AppLeasesNewRoute
  '/app/maintenance/$workOrderId': typeof AppMaintenanceWorkOrderIdRoute
  '/app/maintenance/new': typeof AppMaintenanceNewRoute
  '/app/properties/$propertyId': typeof AppPropertiesPropertyIdRouteWithChildren
  '/app/properties/new': typeof AppPropertiesNewRoute
  '/app/tenants/$tenantId': typeof AppTenantsTenantIdRoute
  '/app/tenants/new': typeof AppTenantsNewRoute
  '/auth/sign-up/profile': typeof AuthSignUpProfileRoute
  '/auth/sign-up/verify': typeof AuthSignUpVerifyRoute
  '/auth/sign-up/welcome': typeof AuthSignUpWelcomeRoute
  '/app/financials/': typeof AppFinancialsIndexRoute
  '/app/leases/': typeof AppLeasesIndexRoute
  '/app/maintenance/': typeof AppMaintenanceIndexRoute
  '/app/properties/': typeof AppPropertiesIndexRoute
  '/app/tenants/': typeof AppTenantsIndexRoute
  '/app/properties/$propertyId/units': typeof AppPropertiesPropertyIdUnitsRoute
  '/app/properties/$propertyId/': typeof AppPropertiesPropertyIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/example-form': typeof examplesExampleFormRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/user-management': typeof AdminUserManagementRoute
  '/app/communications': typeof AppCommunicationsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRouteWithChildren
  '/user/account-settings': typeof UserAccountSettingsRoute
  '/user/change-email': typeof UserChangeEmailRoute
  '/user/change-password': typeof UserChangePasswordRoute
  '/user/email-verification': typeof UserEmailVerificationRoute
  '/app/financials/expenses': typeof AppFinancialsExpensesRoute
  '/app/financials/payments': typeof AppFinancialsPaymentsRoute
  '/app/leases/$leaseId': typeof AppLeasesLeaseIdRoute
  '/app/leases/new': typeof AppLeasesNewRoute
  '/app/maintenance/$workOrderId': typeof AppMaintenanceWorkOrderIdRoute
  '/app/maintenance/new': typeof AppMaintenanceNewRoute
  '/app/properties/new': typeof AppPropertiesNewRoute
  '/app/tenants/$tenantId': typeof AppTenantsTenantIdRoute
  '/app/tenants/new': typeof AppTenantsNewRoute
  '/auth/sign-up/profile': typeof AuthSignUpProfileRoute
  '/auth/sign-up/verify': typeof AuthSignUpVerifyRoute
  '/auth/sign-up/welcome': typeof AuthSignUpWelcomeRoute
  '/app/financials': typeof AppFinancialsIndexRoute
  '/app/leases': typeof AppLeasesIndexRoute
  '/app/maintenance': typeof AppMaintenanceIndexRoute
  '/app/properties': typeof AppPropertiesIndexRoute
  '/app/tenants': typeof AppTenantsIndexRoute
  '/app/properties/$propertyId/units': typeof AppPropertiesPropertyIdUnitsRoute
  '/app/properties/$propertyId': typeof AppPropertiesPropertyIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/(examples)/example-form': typeof examplesExampleFormRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/user-management': typeof AdminUserManagementRoute
  '/app/communications': typeof AppCommunicationsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/financials': typeof AppFinancialsRouteWithChildren
  '/app/leases': typeof AppLeasesRouteWithChildren
  '/app/maintenance': typeof AppMaintenanceRouteWithChildren
  '/app/properties': typeof AppPropertiesRouteWithChildren
  '/app/tenants': typeof AppTenantsRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRouteWithChildren
  '/user/account-settings': typeof UserAccountSettingsRoute
  '/user/change-email': typeof UserChangeEmailRoute
  '/user/change-password': typeof UserChangePasswordRoute
  '/user/email-verification': typeof UserEmailVerificationRoute
  '/app/financials/expenses': typeof AppFinancialsExpensesRoute
  '/app/financials/payments': typeof AppFinancialsPaymentsRoute
  '/app/leases/$leaseId': typeof AppLeasesLeaseIdRoute
  '/app/leases/new': typeof AppLeasesNewRoute
  '/app/maintenance/$workOrderId': typeof AppMaintenanceWorkOrderIdRoute
  '/app/maintenance/new': typeof AppMaintenanceNewRoute
  '/app/properties/$propertyId': typeof AppPropertiesPropertyIdRouteWithChildren
  '/app/properties/new': typeof AppPropertiesNewRoute
  '/app/tenants/$tenantId': typeof AppTenantsTenantIdRoute
  '/app/tenants/new': typeof AppTenantsNewRoute
  '/auth/sign-up/profile': typeof AuthSignUpProfileRoute
  '/auth/sign-up/verify': typeof AuthSignUpVerifyRoute
  '/auth/sign-up/welcome': typeof AuthSignUpWelcomeRoute
  '/app/financials/': typeof AppFinancialsIndexRoute
  '/app/leases/': typeof AppLeasesIndexRoute
  '/app/maintenance/': typeof AppMaintenanceIndexRoute
  '/app/properties/': typeof AppPropertiesIndexRoute
  '/app/tenants/': typeof AppTenantsIndexRoute
  '/app/properties/$propertyId/units': typeof AppPropertiesPropertyIdUnitsRoute
  '/app/properties/$propertyId/': typeof AppPropertiesPropertyIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/user'
    | '/example-form'
    | '/admin/dashboard'
    | '/admin/user-management'
    | '/app/communications'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/financials'
    | '/app/leases'
    | '/app/maintenance'
    | '/app/properties'
    | '/app/tenants'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/user/account-settings'
    | '/user/change-email'
    | '/user/change-password'
    | '/user/email-verification'
    | '/app/financials/expenses'
    | '/app/financials/payments'
    | '/app/leases/$leaseId'
    | '/app/leases/new'
    | '/app/maintenance/$workOrderId'
    | '/app/maintenance/new'
    | '/app/properties/$propertyId'
    | '/app/properties/new'
    | '/app/tenants/$tenantId'
    | '/app/tenants/new'
    | '/auth/sign-up/profile'
    | '/auth/sign-up/verify'
    | '/auth/sign-up/welcome'
    | '/app/financials/'
    | '/app/leases/'
    | '/app/maintenance/'
    | '/app/properties/'
    | '/app/tenants/'
    | '/app/properties/$propertyId/units'
    | '/app/properties/$propertyId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/user'
    | '/example-form'
    | '/admin/dashboard'
    | '/admin/user-management'
    | '/app/communications'
    | '/app/dashboard'
    | '/app/documents'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/user/account-settings'
    | '/user/change-email'
    | '/user/change-password'
    | '/user/email-verification'
    | '/app/financials/expenses'
    | '/app/financials/payments'
    | '/app/leases/$leaseId'
    | '/app/leases/new'
    | '/app/maintenance/$workOrderId'
    | '/app/maintenance/new'
    | '/app/properties/new'
    | '/app/tenants/$tenantId'
    | '/app/tenants/new'
    | '/auth/sign-up/profile'
    | '/auth/sign-up/verify'
    | '/auth/sign-up/welcome'
    | '/app/financials'
    | '/app/leases'
    | '/app/maintenance'
    | '/app/properties'
    | '/app/tenants'
    | '/app/properties/$propertyId/units'
    | '/app/properties/$propertyId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/user'
    | '/(examples)/example-form'
    | '/admin/dashboard'
    | '/admin/user-management'
    | '/app/communications'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/financials'
    | '/app/leases'
    | '/app/maintenance'
    | '/app/properties'
    | '/app/tenants'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/user/account-settings'
    | '/user/change-email'
    | '/user/change-password'
    | '/user/email-verification'
    | '/app/financials/expenses'
    | '/app/financials/payments'
    | '/app/leases/$leaseId'
    | '/app/leases/new'
    | '/app/maintenance/$workOrderId'
    | '/app/maintenance/new'
    | '/app/properties/$propertyId'
    | '/app/properties/new'
    | '/app/tenants/$tenantId'
    | '/app/tenants/new'
    | '/auth/sign-up/profile'
    | '/auth/sign-up/verify'
    | '/auth/sign-up/welcome'
    | '/app/financials/'
    | '/app/leases/'
    | '/app/maintenance/'
    | '/app/properties/'
    | '/app/tenants/'
    | '/app/properties/$propertyId/units'
    | '/app/properties/$propertyId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  UserRoute: typeof UserRouteWithChildren
  examplesExampleFormRoute: typeof examplesExampleFormRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  UserRoute: UserRouteWithChildren,
  examplesExampleFormRoute: examplesExampleFormRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/app",
        "/auth",
        "/user",
        "/(examples)/example-form"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin.tsx",
      "children": [
        "/admin/dashboard",
        "/admin/user-management"
      ]
    },
    "/app": {
      "filePath": "app.tsx",
      "children": [
        "/app/communications",
        "/app/dashboard",
        "/app/documents",
        "/app/financials",
        "/app/leases",
        "/app/maintenance",
        "/app/properties",
        "/app/tenants"
      ]
    },
    "/auth": {
      "filePath": "auth.tsx",
      "children": [
        "/auth/sign-in",
        "/auth/sign-up"
      ]
    },
    "/user": {
      "filePath": "user.tsx",
      "children": [
        "/user/account-settings",
        "/user/change-email",
        "/user/change-password",
        "/user/email-verification"
      ]
    },
    "/(examples)/example-form": {
      "filePath": "(examples)/example-form.tsx"
    },
    "/admin/dashboard": {
      "filePath": "admin.dashboard.tsx",
      "parent": "/admin"
    },
    "/admin/user-management": {
      "filePath": "admin.user-management.tsx",
      "parent": "/admin"
    },
    "/app/communications": {
      "filePath": "app.communications.tsx",
      "parent": "/app"
    },
    "/app/dashboard": {
      "filePath": "app.dashboard.tsx",
      "parent": "/app"
    },
    "/app/documents": {
      "filePath": "app.documents.tsx",
      "parent": "/app"
    },
    "/app/financials": {
      "filePath": "app.financials.tsx",
      "parent": "/app",
      "children": [
        "/app/financials/expenses",
        "/app/financials/payments",
        "/app/financials/"
      ]
    },
    "/app/leases": {
      "filePath": "app.leases.tsx",
      "parent": "/app",
      "children": [
        "/app/leases/$leaseId",
        "/app/leases/new",
        "/app/leases/"
      ]
    },
    "/app/maintenance": {
      "filePath": "app.maintenance.tsx",
      "parent": "/app",
      "children": [
        "/app/maintenance/$workOrderId",
        "/app/maintenance/new",
        "/app/maintenance/"
      ]
    },
    "/app/properties": {
      "filePath": "app.properties.tsx",
      "parent": "/app",
      "children": [
        "/app/properties/$propertyId",
        "/app/properties/new",
        "/app/properties/"
      ]
    },
    "/app/tenants": {
      "filePath": "app.tenants.tsx",
      "parent": "/app",
      "children": [
        "/app/tenants/$tenantId",
        "/app/tenants/new",
        "/app/tenants/"
      ]
    },
    "/auth/sign-in": {
      "filePath": "auth.sign-in.tsx",
      "parent": "/auth"
    },
    "/auth/sign-up": {
      "filePath": "auth.sign-up.tsx",
      "parent": "/auth",
      "children": [
        "/auth/sign-up/profile",
        "/auth/sign-up/verify",
        "/auth/sign-up/welcome"
      ]
    },
    "/user/account-settings": {
      "filePath": "user.account-settings.tsx",
      "parent": "/user"
    },
    "/user/change-email": {
      "filePath": "user.change-email.tsx",
      "parent": "/user"
    },
    "/user/change-password": {
      "filePath": "user.change-password.tsx",
      "parent": "/user"
    },
    "/user/email-verification": {
      "filePath": "user.email-verification.tsx",
      "parent": "/user"
    },
    "/app/financials/expenses": {
      "filePath": "app.financials.expenses.tsx",
      "parent": "/app/financials"
    },
    "/app/financials/payments": {
      "filePath": "app.financials.payments.tsx",
      "parent": "/app/financials"
    },
    "/app/leases/$leaseId": {
      "filePath": "app.leases.$leaseId.tsx",
      "parent": "/app/leases"
    },
    "/app/leases/new": {
      "filePath": "app.leases.new.tsx",
      "parent": "/app/leases"
    },
    "/app/maintenance/$workOrderId": {
      "filePath": "app.maintenance.$workOrderId.tsx",
      "parent": "/app/maintenance"
    },
    "/app/maintenance/new": {
      "filePath": "app.maintenance.new.tsx",
      "parent": "/app/maintenance"
    },
    "/app/properties/$propertyId": {
      "filePath": "app.properties.$propertyId.tsx",
      "parent": "/app/properties",
      "children": [
        "/app/properties/$propertyId/units",
        "/app/properties/$propertyId/"
      ]
    },
    "/app/properties/new": {
      "filePath": "app.properties.new.tsx",
      "parent": "/app/properties"
    },
    "/app/tenants/$tenantId": {
      "filePath": "app.tenants.$tenantId.tsx",
      "parent": "/app/tenants"
    },
    "/app/tenants/new": {
      "filePath": "app.tenants.new.tsx",
      "parent": "/app/tenants"
    },
    "/auth/sign-up/profile": {
      "filePath": "auth.sign-up.profile.tsx",
      "parent": "/auth/sign-up"
    },
    "/auth/sign-up/verify": {
      "filePath": "auth.sign-up.verify.tsx",
      "parent": "/auth/sign-up"
    },
    "/auth/sign-up/welcome": {
      "filePath": "auth.sign-up.welcome.tsx",
      "parent": "/auth/sign-up"
    },
    "/app/financials/": {
      "filePath": "app.financials.index.tsx",
      "parent": "/app/financials"
    },
    "/app/leases/": {
      "filePath": "app.leases.index.tsx",
      "parent": "/app/leases"
    },
    "/app/maintenance/": {
      "filePath": "app.maintenance.index.tsx",
      "parent": "/app/maintenance"
    },
    "/app/properties/": {
      "filePath": "app.properties.index.tsx",
      "parent": "/app/properties"
    },
    "/app/tenants/": {
      "filePath": "app.tenants.index.tsx",
      "parent": "/app/tenants"
    },
    "/app/properties/$propertyId/units": {
      "filePath": "app.properties.$propertyId.units.tsx",
      "parent": "/app/properties/$propertyId"
    },
    "/app/properties/$propertyId/": {
      "filePath": "app.properties.$propertyId.index.tsx",
      "parent": "/app/properties/$propertyId"
    }
  }
}
ROUTE_MANIFEST_END */
