/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UserImport } from './routes/user'
import { Route as TenantImport } from './routes/tenant'
import { Route as AuthImport } from './routes/auth'
import { Route as AppImport } from './routes/app'
import { Route as AdminImport } from './routes/admin'
import { Route as IndexImport } from './routes/index'
import { Route as UserEmailVerificationImport } from './routes/user.email-verification'
import { Route as UserChangePasswordImport } from './routes/user.change-password'
import { Route as UserChangeEmailImport } from './routes/user.change-email'
import { Route as UserAccountSettingsImport } from './routes/user.account-settings'
import { Route as TenantPaymentsImport } from './routes/tenant.payments'
import { Route as TenantDashboardImport } from './routes/tenant.dashboard'
import { Route as AuthSignUpImport } from './routes/auth.sign-up'
import { Route as AuthSignInImport } from './routes/auth.sign-in'
import { Route as AppTenantsImport } from './routes/app.tenants'
import { Route as AppPropertiesImport } from './routes/app.properties'
import { Route as AppPetsImport } from './routes/app.pets'
import { Route as AppMaintenanceImport } from './routes/app.maintenance'
import { Route as AppLeasesImport } from './routes/app.leases'
import { Route as AppFinancialsImport } from './routes/app.financials'
import { Route as AppDocumentsImport } from './routes/app.documents'
import { Route as AppDashboardImport } from './routes/app.dashboard'
import { Route as AppCommunicationsImport } from './routes/app.communications'
import { Route as AdminUserManagementImport } from './routes/admin.user-management'
import { Route as AdminDashboardImport } from './routes/admin.dashboard'
import { Route as examplesExampleFormImport } from './routes/(examples)/example-form'
import { Route as AppTenantsIndexImport } from './routes/app.tenants.index'
import { Route as AppPropertiesIndexImport } from './routes/app.properties.index'
import { Route as AppMaintenanceIndexImport } from './routes/app.maintenance.index'
import { Route as AppLeasesIndexImport } from './routes/app.leases.index'
import { Route as AppInspectionsIndexImport } from './routes/app.inspections.index'
import { Route as AppFinancialsIndexImport } from './routes/app.financials.index'
import { Route as TenantPaymentsSuccessImport } from './routes/tenant.payments.success'
import { Route as TenantPaymentsCancelImport } from './routes/tenant.payments.cancel'
import { Route as AuthSignUpWelcomeImport } from './routes/auth.sign-up.welcome'
import { Route as AuthSignUpVerifyImport } from './routes/auth.sign-up.verify'
import { Route as AuthSignUpProfileImport } from './routes/auth.sign-up.profile'
import { Route as AppTenantsNewImport } from './routes/app.tenants.new'
import { Route as AppTenantsTenantIdImport } from './routes/app.tenants.$tenantId'
import { Route as AppPropertiesNewImport } from './routes/app.properties.new'
import { Route as AppPropertiesPropertyIdImport } from './routes/app.properties.$propertyId'
import { Route as AppMoveOutLeaseIdImport } from './routes/app.move-out.$leaseId'
import { Route as AppMaintenanceVendorsImport } from './routes/app.maintenance.vendors'
import { Route as AppMaintenanceSchedulesImport } from './routes/app.maintenance.schedules'
import { Route as AppMaintenanceCostsImport } from './routes/app.maintenance.costs'
import { Route as AppMaintenanceBudgetsImport } from './routes/app.maintenance.budgets'
import { Route as AppMaintenanceWorkOrderIdImport } from './routes/app.maintenance.$workOrderId'
import { Route as AppLeasesTemplatesImport } from './routes/app.leases.templates'
import { Route as AppLeasesNewImport } from './routes/app.leases.new'
import { Route as AppLeasesLeaseIdImport } from './routes/app.leases.$leaseId'
import { Route as AppInspectionsNewImport } from './routes/app.inspections.new'
import { Route as AppInspectionsInspectionIdImport } from './routes/app.inspections.$inspectionId'
import { Route as AppFinancialsPaymentsImport } from './routes/app.financials.payments'
import { Route as AppFinancialsExpensesImport } from './routes/app.financials.expenses'
import { Route as AppFinancialsDepositsImport } from './routes/app.financials.deposits'
import { Route as AppPropertiesPropertyIdIndexImport } from './routes/app.properties.$propertyId.index'
import { Route as AppPropertiesPropertyIdUnitsImport } from './routes/app.properties.$propertyId.units'
import { Route as AppPropertiesPropertyIdEditImport } from './routes/app.properties.$propertyId.edit'
import { Route as AppMaintenanceVendorsVendorIdImport } from './routes/app.maintenance.vendors.$vendorId'
import { Route as AppMaintenanceSchedulesScheduleIdImport } from './routes/app.maintenance.schedules.$scheduleId'
import { Route as AppMaintenanceBudgetsComparisonImport } from './routes/app.maintenance.budgets.comparison'
import { Route as AppMaintenanceBudgetsBudgetIdImport } from './routes/app.maintenance.budgets.$budgetId'
import { Route as AppPropertiesPropertyIdUnitsNewImport } from './routes/app.properties.$propertyId.units.new'
import { Route as AppPropertiesPropertyIdUnitsUnitIdEditImport } from './routes/app.properties.$propertyId.units.$unitId.edit'

// Create/Update Routes

const UserRoute = UserImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRoute,
} as any)

const TenantRoute = TenantImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UserEmailVerificationRoute = UserEmailVerificationImport.update({
  id: '/email-verification',
  path: '/email-verification',
  getParentRoute: () => UserRoute,
} as any)

const UserChangePasswordRoute = UserChangePasswordImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => UserRoute,
} as any)

const UserChangeEmailRoute = UserChangeEmailImport.update({
  id: '/change-email',
  path: '/change-email',
  getParentRoute: () => UserRoute,
} as any)

const UserAccountSettingsRoute = UserAccountSettingsImport.update({
  id: '/account-settings',
  path: '/account-settings',
  getParentRoute: () => UserRoute,
} as any)

const TenantPaymentsRoute = TenantPaymentsImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => TenantRoute,
} as any)

const TenantDashboardRoute = TenantDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => TenantRoute,
} as any)

const AuthSignUpRoute = AuthSignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)

const AuthSignInRoute = AuthSignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)

const AppTenantsRoute = AppTenantsImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AppRoute,
} as any)

const AppPropertiesRoute = AppPropertiesImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AppRoute,
} as any)

const AppPetsRoute = AppPetsImport.update({
  id: '/pets',
  path: '/pets',
  getParentRoute: () => AppRoute,
} as any)

const AppMaintenanceRoute = AppMaintenanceImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AppRoute,
} as any)

const AppLeasesRoute = AppLeasesImport.update({
  id: '/leases',
  path: '/leases',
  getParentRoute: () => AppRoute,
} as any)

const AppFinancialsRoute = AppFinancialsImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => AppRoute,
} as any)

const AppDocumentsRoute = AppDocumentsImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)

const AppDashboardRoute = AppDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)

const AppCommunicationsRoute = AppCommunicationsImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => AppRoute,
} as any)

const AdminUserManagementRoute = AdminUserManagementImport.update({
  id: '/user-management',
  path: '/user-management',
  getParentRoute: () => AdminRoute,
} as any)

const AdminDashboardRoute = AdminDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)

const examplesExampleFormRoute = examplesExampleFormImport.update({
  id: '/(examples)/example-form',
  path: '/example-form',
  getParentRoute: () => rootRoute,
} as any)

const AppTenantsIndexRoute = AppTenantsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTenantsRoute,
} as any)

const AppPropertiesIndexRoute = AppPropertiesIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPropertiesRoute,
} as any)

const AppMaintenanceIndexRoute = AppMaintenanceIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMaintenanceRoute,
} as any)

const AppLeasesIndexRoute = AppLeasesIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLeasesRoute,
} as any)

const AppInspectionsIndexRoute = AppInspectionsIndexImport.update({
  id: '/inspections/',
  path: '/inspections/',
  getParentRoute: () => AppRoute,
} as any)

const AppFinancialsIndexRoute = AppFinancialsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFinancialsRoute,
} as any)

const TenantPaymentsSuccessRoute = TenantPaymentsSuccessImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => TenantPaymentsRoute,
} as any)

const TenantPaymentsCancelRoute = TenantPaymentsCancelImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => TenantPaymentsRoute,
} as any)

const AuthSignUpWelcomeRoute = AuthSignUpWelcomeImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthSignUpRoute,
} as any)

const AuthSignUpVerifyRoute = AuthSignUpVerifyImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthSignUpRoute,
} as any)

const AuthSignUpProfileRoute = AuthSignUpProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthSignUpRoute,
} as any)

const AppTenantsNewRoute = AppTenantsNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppTenantsRoute,
} as any)

const AppTenantsTenantIdRoute = AppTenantsTenantIdImport.update({
  id: '/$tenantId',
  path: '/$tenantId',
  getParentRoute: () => AppTenantsRoute,
} as any)

const AppPropertiesNewRoute = AppPropertiesNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppPropertiesRoute,
} as any)

const AppPropertiesPropertyIdRoute = AppPropertiesPropertyIdImport.update({
  id: '/$propertyId',
  path: '/$propertyId',
  getParentRoute: () => AppPropertiesRoute,
} as any)

const AppMoveOutLeaseIdRoute = AppMoveOutLeaseIdImport.update({
  id: '/move-out/$leaseId',
  path: '/move-out/$leaseId',
  getParentRoute: () => AppRoute,
} as any)

const AppMaintenanceVendorsRoute = AppMaintenanceVendorsImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AppMaintenanceRoute,
} as any)

const AppMaintenanceSchedulesRoute = AppMaintenanceSchedulesImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AppMaintenanceRoute,
} as any)

const AppMaintenanceCostsRoute = AppMaintenanceCostsImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => AppMaintenanceRoute,
} as any)

const AppMaintenanceBudgetsRoute = AppMaintenanceBudgetsImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => AppMaintenanceRoute,
} as any)

const AppMaintenanceWorkOrderIdRoute = AppMaintenanceWorkOrderIdImport.update({
  id: '/$workOrderId',
  path: '/$workOrderId',
  getParentRoute: () => AppMaintenanceRoute,
} as any)

const AppLeasesTemplatesRoute = AppLeasesTemplatesImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppLeasesRoute,
} as any)

const AppLeasesNewRoute = AppLeasesNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppLeasesRoute,
} as any)

const AppLeasesLeaseIdRoute = AppLeasesLeaseIdImport.update({
  id: '/$leaseId',
  path: '/$leaseId',
  getParentRoute: () => AppLeasesRoute,
} as any)

const AppInspectionsNewRoute = AppInspectionsNewImport.update({
  id: '/inspections/new',
  path: '/inspections/new',
  getParentRoute: () => AppRoute,
} as any)

const AppInspectionsInspectionIdRoute = AppInspectionsInspectionIdImport.update(
  {
    id: '/inspections/$inspectionId',
    path: '/inspections/$inspectionId',
    getParentRoute: () => AppRoute,
  } as any,
)

const AppFinancialsPaymentsRoute = AppFinancialsPaymentsImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppFinancialsRoute,
} as any)

const AppFinancialsExpensesRoute = AppFinancialsExpensesImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppFinancialsRoute,
} as any)

const AppFinancialsDepositsRoute = AppFinancialsDepositsImport.update({
  id: '/deposits',
  path: '/deposits',
  getParentRoute: () => AppFinancialsRoute,
} as any)

const AppPropertiesPropertyIdIndexRoute =
  AppPropertiesPropertyIdIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppPropertiesPropertyIdRoute,
  } as any)

const AppPropertiesPropertyIdUnitsRoute =
  AppPropertiesPropertyIdUnitsImport.update({
    id: '/units',
    path: '/units',
    getParentRoute: () => AppPropertiesPropertyIdRoute,
  } as any)

const AppPropertiesPropertyIdEditRoute =
  AppPropertiesPropertyIdEditImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppPropertiesPropertyIdRoute,
  } as any)

const AppMaintenanceVendorsVendorIdRoute =
  AppMaintenanceVendorsVendorIdImport.update({
    id: '/$vendorId',
    path: '/$vendorId',
    getParentRoute: () => AppMaintenanceVendorsRoute,
  } as any)

const AppMaintenanceSchedulesScheduleIdRoute =
  AppMaintenanceSchedulesScheduleIdImport.update({
    id: '/$scheduleId',
    path: '/$scheduleId',
    getParentRoute: () => AppMaintenanceSchedulesRoute,
  } as any)

const AppMaintenanceBudgetsComparisonRoute =
  AppMaintenanceBudgetsComparisonImport.update({
    id: '/comparison',
    path: '/comparison',
    getParentRoute: () => AppMaintenanceBudgetsRoute,
  } as any)

const AppMaintenanceBudgetsBudgetIdRoute =
  AppMaintenanceBudgetsBudgetIdImport.update({
    id: '/$budgetId',
    path: '/$budgetId',
    getParentRoute: () => AppMaintenanceBudgetsRoute,
  } as any)

const AppPropertiesPropertyIdUnitsNewRoute =
  AppPropertiesPropertyIdUnitsNewImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AppPropertiesPropertyIdUnitsRoute,
  } as any)

const AppPropertiesPropertyIdUnitsUnitIdEditRoute =
  AppPropertiesPropertyIdUnitsUnitIdEditImport.update({
    id: '/$unitId/edit',
    path: '/$unitId/edit',
    getParentRoute: () => AppPropertiesPropertyIdUnitsRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/tenant': {
      id: '/tenant'
      path: '/tenant'
      fullPath: '/tenant'
      preLoaderRoute: typeof TenantImport
      parentRoute: typeof rootRoute
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserImport
      parentRoute: typeof rootRoute
    }
    '/(examples)/example-form': {
      id: '/(examples)/example-form'
      path: '/example-form'
      fullPath: '/example-form'
      preLoaderRoute: typeof examplesExampleFormImport
      parentRoute: typeof rootRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardImport
      parentRoute: typeof AdminImport
    }
    '/admin/user-management': {
      id: '/admin/user-management'
      path: '/user-management'
      fullPath: '/admin/user-management'
      preLoaderRoute: typeof AdminUserManagementImport
      parentRoute: typeof AdminImport
    }
    '/app/communications': {
      id: '/app/communications'
      path: '/communications'
      fullPath: '/app/communications'
      preLoaderRoute: typeof AppCommunicationsImport
      parentRoute: typeof AppImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardImport
      parentRoute: typeof AppImport
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsImport
      parentRoute: typeof AppImport
    }
    '/app/financials': {
      id: '/app/financials'
      path: '/financials'
      fullPath: '/app/financials'
      preLoaderRoute: typeof AppFinancialsImport
      parentRoute: typeof AppImport
    }
    '/app/leases': {
      id: '/app/leases'
      path: '/leases'
      fullPath: '/app/leases'
      preLoaderRoute: typeof AppLeasesImport
      parentRoute: typeof AppImport
    }
    '/app/maintenance': {
      id: '/app/maintenance'
      path: '/maintenance'
      fullPath: '/app/maintenance'
      preLoaderRoute: typeof AppMaintenanceImport
      parentRoute: typeof AppImport
    }
    '/app/pets': {
      id: '/app/pets'
      path: '/pets'
      fullPath: '/app/pets'
      preLoaderRoute: typeof AppPetsImport
      parentRoute: typeof AppImport
    }
    '/app/properties': {
      id: '/app/properties'
      path: '/properties'
      fullPath: '/app/properties'
      preLoaderRoute: typeof AppPropertiesImport
      parentRoute: typeof AppImport
    }
    '/app/tenants': {
      id: '/app/tenants'
      path: '/tenants'
      fullPath: '/app/tenants'
      preLoaderRoute: typeof AppTenantsImport
      parentRoute: typeof AppImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInImport
      parentRoute: typeof AuthImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpImport
      parentRoute: typeof AuthImport
    }
    '/tenant/dashboard': {
      id: '/tenant/dashboard'
      path: '/dashboard'
      fullPath: '/tenant/dashboard'
      preLoaderRoute: typeof TenantDashboardImport
      parentRoute: typeof TenantImport
    }
    '/tenant/payments': {
      id: '/tenant/payments'
      path: '/payments'
      fullPath: '/tenant/payments'
      preLoaderRoute: typeof TenantPaymentsImport
      parentRoute: typeof TenantImport
    }
    '/user/account-settings': {
      id: '/user/account-settings'
      path: '/account-settings'
      fullPath: '/user/account-settings'
      preLoaderRoute: typeof UserAccountSettingsImport
      parentRoute: typeof UserImport
    }
    '/user/change-email': {
      id: '/user/change-email'
      path: '/change-email'
      fullPath: '/user/change-email'
      preLoaderRoute: typeof UserChangeEmailImport
      parentRoute: typeof UserImport
    }
    '/user/change-password': {
      id: '/user/change-password'
      path: '/change-password'
      fullPath: '/user/change-password'
      preLoaderRoute: typeof UserChangePasswordImport
      parentRoute: typeof UserImport
    }
    '/user/email-verification': {
      id: '/user/email-verification'
      path: '/email-verification'
      fullPath: '/user/email-verification'
      preLoaderRoute: typeof UserEmailVerificationImport
      parentRoute: typeof UserImport
    }
    '/app/financials/deposits': {
      id: '/app/financials/deposits'
      path: '/deposits'
      fullPath: '/app/financials/deposits'
      preLoaderRoute: typeof AppFinancialsDepositsImport
      parentRoute: typeof AppFinancialsImport
    }
    '/app/financials/expenses': {
      id: '/app/financials/expenses'
      path: '/expenses'
      fullPath: '/app/financials/expenses'
      preLoaderRoute: typeof AppFinancialsExpensesImport
      parentRoute: typeof AppFinancialsImport
    }
    '/app/financials/payments': {
      id: '/app/financials/payments'
      path: '/payments'
      fullPath: '/app/financials/payments'
      preLoaderRoute: typeof AppFinancialsPaymentsImport
      parentRoute: typeof AppFinancialsImport
    }
    '/app/inspections/$inspectionId': {
      id: '/app/inspections/$inspectionId'
      path: '/inspections/$inspectionId'
      fullPath: '/app/inspections/$inspectionId'
      preLoaderRoute: typeof AppInspectionsInspectionIdImport
      parentRoute: typeof AppImport
    }
    '/app/inspections/new': {
      id: '/app/inspections/new'
      path: '/inspections/new'
      fullPath: '/app/inspections/new'
      preLoaderRoute: typeof AppInspectionsNewImport
      parentRoute: typeof AppImport
    }
    '/app/leases/$leaseId': {
      id: '/app/leases/$leaseId'
      path: '/$leaseId'
      fullPath: '/app/leases/$leaseId'
      preLoaderRoute: typeof AppLeasesLeaseIdImport
      parentRoute: typeof AppLeasesImport
    }
    '/app/leases/new': {
      id: '/app/leases/new'
      path: '/new'
      fullPath: '/app/leases/new'
      preLoaderRoute: typeof AppLeasesNewImport
      parentRoute: typeof AppLeasesImport
    }
    '/app/leases/templates': {
      id: '/app/leases/templates'
      path: '/templates'
      fullPath: '/app/leases/templates'
      preLoaderRoute: typeof AppLeasesTemplatesImport
      parentRoute: typeof AppLeasesImport
    }
    '/app/maintenance/$workOrderId': {
      id: '/app/maintenance/$workOrderId'
      path: '/$workOrderId'
      fullPath: '/app/maintenance/$workOrderId'
      preLoaderRoute: typeof AppMaintenanceWorkOrderIdImport
      parentRoute: typeof AppMaintenanceImport
    }
    '/app/maintenance/budgets': {
      id: '/app/maintenance/budgets'
      path: '/budgets'
      fullPath: '/app/maintenance/budgets'
      preLoaderRoute: typeof AppMaintenanceBudgetsImport
      parentRoute: typeof AppMaintenanceImport
    }
    '/app/maintenance/costs': {
      id: '/app/maintenance/costs'
      path: '/costs'
      fullPath: '/app/maintenance/costs'
      preLoaderRoute: typeof AppMaintenanceCostsImport
      parentRoute: typeof AppMaintenanceImport
    }
    '/app/maintenance/schedules': {
      id: '/app/maintenance/schedules'
      path: '/schedules'
      fullPath: '/app/maintenance/schedules'
      preLoaderRoute: typeof AppMaintenanceSchedulesImport
      parentRoute: typeof AppMaintenanceImport
    }
    '/app/maintenance/vendors': {
      id: '/app/maintenance/vendors'
      path: '/vendors'
      fullPath: '/app/maintenance/vendors'
      preLoaderRoute: typeof AppMaintenanceVendorsImport
      parentRoute: typeof AppMaintenanceImport
    }
    '/app/move-out/$leaseId': {
      id: '/app/move-out/$leaseId'
      path: '/move-out/$leaseId'
      fullPath: '/app/move-out/$leaseId'
      preLoaderRoute: typeof AppMoveOutLeaseIdImport
      parentRoute: typeof AppImport
    }
    '/app/properties/$propertyId': {
      id: '/app/properties/$propertyId'
      path: '/$propertyId'
      fullPath: '/app/properties/$propertyId'
      preLoaderRoute: typeof AppPropertiesPropertyIdImport
      parentRoute: typeof AppPropertiesImport
    }
    '/app/properties/new': {
      id: '/app/properties/new'
      path: '/new'
      fullPath: '/app/properties/new'
      preLoaderRoute: typeof AppPropertiesNewImport
      parentRoute: typeof AppPropertiesImport
    }
    '/app/tenants/$tenantId': {
      id: '/app/tenants/$tenantId'
      path: '/$tenantId'
      fullPath: '/app/tenants/$tenantId'
      preLoaderRoute: typeof AppTenantsTenantIdImport
      parentRoute: typeof AppTenantsImport
    }
    '/app/tenants/new': {
      id: '/app/tenants/new'
      path: '/new'
      fullPath: '/app/tenants/new'
      preLoaderRoute: typeof AppTenantsNewImport
      parentRoute: typeof AppTenantsImport
    }
    '/auth/sign-up/profile': {
      id: '/auth/sign-up/profile'
      path: '/profile'
      fullPath: '/auth/sign-up/profile'
      preLoaderRoute: typeof AuthSignUpProfileImport
      parentRoute: typeof AuthSignUpImport
    }
    '/auth/sign-up/verify': {
      id: '/auth/sign-up/verify'
      path: '/verify'
      fullPath: '/auth/sign-up/verify'
      preLoaderRoute: typeof AuthSignUpVerifyImport
      parentRoute: typeof AuthSignUpImport
    }
    '/auth/sign-up/welcome': {
      id: '/auth/sign-up/welcome'
      path: '/welcome'
      fullPath: '/auth/sign-up/welcome'
      preLoaderRoute: typeof AuthSignUpWelcomeImport
      parentRoute: typeof AuthSignUpImport
    }
    '/tenant/payments/cancel': {
      id: '/tenant/payments/cancel'
      path: '/cancel'
      fullPath: '/tenant/payments/cancel'
      preLoaderRoute: typeof TenantPaymentsCancelImport
      parentRoute: typeof TenantPaymentsImport
    }
    '/tenant/payments/success': {
      id: '/tenant/payments/success'
      path: '/success'
      fullPath: '/tenant/payments/success'
      preLoaderRoute: typeof TenantPaymentsSuccessImport
      parentRoute: typeof TenantPaymentsImport
    }
    '/app/financials/': {
      id: '/app/financials/'
      path: '/'
      fullPath: '/app/financials/'
      preLoaderRoute: typeof AppFinancialsIndexImport
      parentRoute: typeof AppFinancialsImport
    }
    '/app/inspections/': {
      id: '/app/inspections/'
      path: '/inspections'
      fullPath: '/app/inspections'
      preLoaderRoute: typeof AppInspectionsIndexImport
      parentRoute: typeof AppImport
    }
    '/app/leases/': {
      id: '/app/leases/'
      path: '/'
      fullPath: '/app/leases/'
      preLoaderRoute: typeof AppLeasesIndexImport
      parentRoute: typeof AppLeasesImport
    }
    '/app/maintenance/': {
      id: '/app/maintenance/'
      path: '/'
      fullPath: '/app/maintenance/'
      preLoaderRoute: typeof AppMaintenanceIndexImport
      parentRoute: typeof AppMaintenanceImport
    }
    '/app/properties/': {
      id: '/app/properties/'
      path: '/'
      fullPath: '/app/properties/'
      preLoaderRoute: typeof AppPropertiesIndexImport
      parentRoute: typeof AppPropertiesImport
    }
    '/app/tenants/': {
      id: '/app/tenants/'
      path: '/'
      fullPath: '/app/tenants/'
      preLoaderRoute: typeof AppTenantsIndexImport
      parentRoute: typeof AppTenantsImport
    }
    '/app/maintenance/budgets/$budgetId': {
      id: '/app/maintenance/budgets/$budgetId'
      path: '/$budgetId'
      fullPath: '/app/maintenance/budgets/$budgetId'
      preLoaderRoute: typeof AppMaintenanceBudgetsBudgetIdImport
      parentRoute: typeof AppMaintenanceBudgetsImport
    }
    '/app/maintenance/budgets/comparison': {
      id: '/app/maintenance/budgets/comparison'
      path: '/comparison'
      fullPath: '/app/maintenance/budgets/comparison'
      preLoaderRoute: typeof AppMaintenanceBudgetsComparisonImport
      parentRoute: typeof AppMaintenanceBudgetsImport
    }
    '/app/maintenance/schedules/$scheduleId': {
      id: '/app/maintenance/schedules/$scheduleId'
      path: '/$scheduleId'
      fullPath: '/app/maintenance/schedules/$scheduleId'
      preLoaderRoute: typeof AppMaintenanceSchedulesScheduleIdImport
      parentRoute: typeof AppMaintenanceSchedulesImport
    }
    '/app/maintenance/vendors/$vendorId': {
      id: '/app/maintenance/vendors/$vendorId'
      path: '/$vendorId'
      fullPath: '/app/maintenance/vendors/$vendorId'
      preLoaderRoute: typeof AppMaintenanceVendorsVendorIdImport
      parentRoute: typeof AppMaintenanceVendorsImport
    }
    '/app/properties/$propertyId/edit': {
      id: '/app/properties/$propertyId/edit'
      path: '/edit'
      fullPath: '/app/properties/$propertyId/edit'
      preLoaderRoute: typeof AppPropertiesPropertyIdEditImport
      parentRoute: typeof AppPropertiesPropertyIdImport
    }
    '/app/properties/$propertyId/units': {
      id: '/app/properties/$propertyId/units'
      path: '/units'
      fullPath: '/app/properties/$propertyId/units'
      preLoaderRoute: typeof AppPropertiesPropertyIdUnitsImport
      parentRoute: typeof AppPropertiesPropertyIdImport
    }
    '/app/properties/$propertyId/': {
      id: '/app/properties/$propertyId/'
      path: '/'
      fullPath: '/app/properties/$propertyId/'
      preLoaderRoute: typeof AppPropertiesPropertyIdIndexImport
      parentRoute: typeof AppPropertiesPropertyIdImport
    }
    '/app/properties/$propertyId/units/new': {
      id: '/app/properties/$propertyId/units/new'
      path: '/new'
      fullPath: '/app/properties/$propertyId/units/new'
      preLoaderRoute: typeof AppPropertiesPropertyIdUnitsNewImport
      parentRoute: typeof AppPropertiesPropertyIdUnitsImport
    }
    '/app/properties/$propertyId/units/$unitId/edit': {
      id: '/app/properties/$propertyId/units/$unitId/edit'
      path: '/$unitId/edit'
      fullPath: '/app/properties/$propertyId/units/$unitId/edit'
      preLoaderRoute: typeof AppPropertiesPropertyIdUnitsUnitIdEditImport
      parentRoute: typeof AppPropertiesPropertyIdUnitsImport
    }
  }
}

// Create and export the route tree

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminUserManagementRoute: typeof AdminUserManagementRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminUserManagementRoute: AdminUserManagementRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppFinancialsRouteChildren {
  AppFinancialsDepositsRoute: typeof AppFinancialsDepositsRoute
  AppFinancialsExpensesRoute: typeof AppFinancialsExpensesRoute
  AppFinancialsPaymentsRoute: typeof AppFinancialsPaymentsRoute
  AppFinancialsIndexRoute: typeof AppFinancialsIndexRoute
}

const AppFinancialsRouteChildren: AppFinancialsRouteChildren = {
  AppFinancialsDepositsRoute: AppFinancialsDepositsRoute,
  AppFinancialsExpensesRoute: AppFinancialsExpensesRoute,
  AppFinancialsPaymentsRoute: AppFinancialsPaymentsRoute,
  AppFinancialsIndexRoute: AppFinancialsIndexRoute,
}

const AppFinancialsRouteWithChildren = AppFinancialsRoute._addFileChildren(
  AppFinancialsRouteChildren,
)

interface AppLeasesRouteChildren {
  AppLeasesLeaseIdRoute: typeof AppLeasesLeaseIdRoute
  AppLeasesNewRoute: typeof AppLeasesNewRoute
  AppLeasesTemplatesRoute: typeof AppLeasesTemplatesRoute
  AppLeasesIndexRoute: typeof AppLeasesIndexRoute
}

const AppLeasesRouteChildren: AppLeasesRouteChildren = {
  AppLeasesLeaseIdRoute: AppLeasesLeaseIdRoute,
  AppLeasesNewRoute: AppLeasesNewRoute,
  AppLeasesTemplatesRoute: AppLeasesTemplatesRoute,
  AppLeasesIndexRoute: AppLeasesIndexRoute,
}

const AppLeasesRouteWithChildren = AppLeasesRoute._addFileChildren(
  AppLeasesRouteChildren,
)

interface AppMaintenanceBudgetsRouteChildren {
  AppMaintenanceBudgetsBudgetIdRoute: typeof AppMaintenanceBudgetsBudgetIdRoute
  AppMaintenanceBudgetsComparisonRoute: typeof AppMaintenanceBudgetsComparisonRoute
}

const AppMaintenanceBudgetsRouteChildren: AppMaintenanceBudgetsRouteChildren = {
  AppMaintenanceBudgetsBudgetIdRoute: AppMaintenanceBudgetsBudgetIdRoute,
  AppMaintenanceBudgetsComparisonRoute: AppMaintenanceBudgetsComparisonRoute,
}

const AppMaintenanceBudgetsRouteWithChildren =
  AppMaintenanceBudgetsRoute._addFileChildren(
    AppMaintenanceBudgetsRouteChildren,
  )

interface AppMaintenanceSchedulesRouteChildren {
  AppMaintenanceSchedulesScheduleIdRoute: typeof AppMaintenanceSchedulesScheduleIdRoute
}

const AppMaintenanceSchedulesRouteChildren: AppMaintenanceSchedulesRouteChildren =
  {
    AppMaintenanceSchedulesScheduleIdRoute:
      AppMaintenanceSchedulesScheduleIdRoute,
  }

const AppMaintenanceSchedulesRouteWithChildren =
  AppMaintenanceSchedulesRoute._addFileChildren(
    AppMaintenanceSchedulesRouteChildren,
  )

interface AppMaintenanceVendorsRouteChildren {
  AppMaintenanceVendorsVendorIdRoute: typeof AppMaintenanceVendorsVendorIdRoute
}

const AppMaintenanceVendorsRouteChildren: AppMaintenanceVendorsRouteChildren = {
  AppMaintenanceVendorsVendorIdRoute: AppMaintenanceVendorsVendorIdRoute,
}

const AppMaintenanceVendorsRouteWithChildren =
  AppMaintenanceVendorsRoute._addFileChildren(
    AppMaintenanceVendorsRouteChildren,
  )

interface AppMaintenanceRouteChildren {
  AppMaintenanceWorkOrderIdRoute: typeof AppMaintenanceWorkOrderIdRoute
  AppMaintenanceBudgetsRoute: typeof AppMaintenanceBudgetsRouteWithChildren
  AppMaintenanceCostsRoute: typeof AppMaintenanceCostsRoute
  AppMaintenanceSchedulesRoute: typeof AppMaintenanceSchedulesRouteWithChildren
  AppMaintenanceVendorsRoute: typeof AppMaintenanceVendorsRouteWithChildren
  AppMaintenanceIndexRoute: typeof AppMaintenanceIndexRoute
}

const AppMaintenanceRouteChildren: AppMaintenanceRouteChildren = {
  AppMaintenanceWorkOrderIdRoute: AppMaintenanceWorkOrderIdRoute,
  AppMaintenanceBudgetsRoute: AppMaintenanceBudgetsRouteWithChildren,
  AppMaintenanceCostsRoute: AppMaintenanceCostsRoute,
  AppMaintenanceSchedulesRoute: AppMaintenanceSchedulesRouteWithChildren,
  AppMaintenanceVendorsRoute: AppMaintenanceVendorsRouteWithChildren,
  AppMaintenanceIndexRoute: AppMaintenanceIndexRoute,
}

const AppMaintenanceRouteWithChildren = AppMaintenanceRoute._addFileChildren(
  AppMaintenanceRouteChildren,
)

interface AppPropertiesPropertyIdUnitsRouteChildren {
  AppPropertiesPropertyIdUnitsNewRoute: typeof AppPropertiesPropertyIdUnitsNewRoute
  AppPropertiesPropertyIdUnitsUnitIdEditRoute: typeof AppPropertiesPropertyIdUnitsUnitIdEditRoute
}

const AppPropertiesPropertyIdUnitsRouteChildren: AppPropertiesPropertyIdUnitsRouteChildren =
  {
    AppPropertiesPropertyIdUnitsNewRoute: AppPropertiesPropertyIdUnitsNewRoute,
    AppPropertiesPropertyIdUnitsUnitIdEditRoute:
      AppPropertiesPropertyIdUnitsUnitIdEditRoute,
  }

const AppPropertiesPropertyIdUnitsRouteWithChildren =
  AppPropertiesPropertyIdUnitsRoute._addFileChildren(
    AppPropertiesPropertyIdUnitsRouteChildren,
  )

interface AppPropertiesPropertyIdRouteChildren {
  AppPropertiesPropertyIdEditRoute: typeof AppPropertiesPropertyIdEditRoute
  AppPropertiesPropertyIdUnitsRoute: typeof AppPropertiesPropertyIdUnitsRouteWithChildren
  AppPropertiesPropertyIdIndexRoute: typeof AppPropertiesPropertyIdIndexRoute
}

const AppPropertiesPropertyIdRouteChildren: AppPropertiesPropertyIdRouteChildren =
  {
    AppPropertiesPropertyIdEditRoute: AppPropertiesPropertyIdEditRoute,
    AppPropertiesPropertyIdUnitsRoute:
      AppPropertiesPropertyIdUnitsRouteWithChildren,
    AppPropertiesPropertyIdIndexRoute: AppPropertiesPropertyIdIndexRoute,
  }

const AppPropertiesPropertyIdRouteWithChildren =
  AppPropertiesPropertyIdRoute._addFileChildren(
    AppPropertiesPropertyIdRouteChildren,
  )

interface AppPropertiesRouteChildren {
  AppPropertiesPropertyIdRoute: typeof AppPropertiesPropertyIdRouteWithChildren
  AppPropertiesNewRoute: typeof AppPropertiesNewRoute
  AppPropertiesIndexRoute: typeof AppPropertiesIndexRoute
}

const AppPropertiesRouteChildren: AppPropertiesRouteChildren = {
  AppPropertiesPropertyIdRoute: AppPropertiesPropertyIdRouteWithChildren,
  AppPropertiesNewRoute: AppPropertiesNewRoute,
  AppPropertiesIndexRoute: AppPropertiesIndexRoute,
}

const AppPropertiesRouteWithChildren = AppPropertiesRoute._addFileChildren(
  AppPropertiesRouteChildren,
)

interface AppTenantsRouteChildren {
  AppTenantsTenantIdRoute: typeof AppTenantsTenantIdRoute
  AppTenantsNewRoute: typeof AppTenantsNewRoute
  AppTenantsIndexRoute: typeof AppTenantsIndexRoute
}

const AppTenantsRouteChildren: AppTenantsRouteChildren = {
  AppTenantsTenantIdRoute: AppTenantsTenantIdRoute,
  AppTenantsNewRoute: AppTenantsNewRoute,
  AppTenantsIndexRoute: AppTenantsIndexRoute,
}

const AppTenantsRouteWithChildren = AppTenantsRoute._addFileChildren(
  AppTenantsRouteChildren,
)

interface AppRouteChildren {
  AppCommunicationsRoute: typeof AppCommunicationsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppFinancialsRoute: typeof AppFinancialsRouteWithChildren
  AppLeasesRoute: typeof AppLeasesRouteWithChildren
  AppMaintenanceRoute: typeof AppMaintenanceRouteWithChildren
  AppPetsRoute: typeof AppPetsRoute
  AppPropertiesRoute: typeof AppPropertiesRouteWithChildren
  AppTenantsRoute: typeof AppTenantsRouteWithChildren
  AppInspectionsInspectionIdRoute: typeof AppInspectionsInspectionIdRoute
  AppInspectionsNewRoute: typeof AppInspectionsNewRoute
  AppMoveOutLeaseIdRoute: typeof AppMoveOutLeaseIdRoute
  AppInspectionsIndexRoute: typeof AppInspectionsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCommunicationsRoute: AppCommunicationsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppFinancialsRoute: AppFinancialsRouteWithChildren,
  AppLeasesRoute: AppLeasesRouteWithChildren,
  AppMaintenanceRoute: AppMaintenanceRouteWithChildren,
  AppPetsRoute: AppPetsRoute,
  AppPropertiesRoute: AppPropertiesRouteWithChildren,
  AppTenantsRoute: AppTenantsRouteWithChildren,
  AppInspectionsInspectionIdRoute: AppInspectionsInspectionIdRoute,
  AppInspectionsNewRoute: AppInspectionsNewRoute,
  AppMoveOutLeaseIdRoute: AppMoveOutLeaseIdRoute,
  AppInspectionsIndexRoute: AppInspectionsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthSignUpRouteChildren {
  AuthSignUpProfileRoute: typeof AuthSignUpProfileRoute
  AuthSignUpVerifyRoute: typeof AuthSignUpVerifyRoute
  AuthSignUpWelcomeRoute: typeof AuthSignUpWelcomeRoute
}

const AuthSignUpRouteChildren: AuthSignUpRouteChildren = {
  AuthSignUpProfileRoute: AuthSignUpProfileRoute,
  AuthSignUpVerifyRoute: AuthSignUpVerifyRoute,
  AuthSignUpWelcomeRoute: AuthSignUpWelcomeRoute,
}

const AuthSignUpRouteWithChildren = AuthSignUpRoute._addFileChildren(
  AuthSignUpRouteChildren,
)

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface TenantPaymentsRouteChildren {
  TenantPaymentsCancelRoute: typeof TenantPaymentsCancelRoute
  TenantPaymentsSuccessRoute: typeof TenantPaymentsSuccessRoute
}

const TenantPaymentsRouteChildren: TenantPaymentsRouteChildren = {
  TenantPaymentsCancelRoute: TenantPaymentsCancelRoute,
  TenantPaymentsSuccessRoute: TenantPaymentsSuccessRoute,
}

const TenantPaymentsRouteWithChildren = TenantPaymentsRoute._addFileChildren(
  TenantPaymentsRouteChildren,
)

interface TenantRouteChildren {
  TenantDashboardRoute: typeof TenantDashboardRoute
  TenantPaymentsRoute: typeof TenantPaymentsRouteWithChildren
}

const TenantRouteChildren: TenantRouteChildren = {
  TenantDashboardRoute: TenantDashboardRoute,
  TenantPaymentsRoute: TenantPaymentsRouteWithChildren,
}

const TenantRouteWithChildren =
  TenantRoute._addFileChildren(TenantRouteChildren)

interface UserRouteChildren {
  UserAccountSettingsRoute: typeof UserAccountSettingsRoute
  UserChangeEmailRoute: typeof UserChangeEmailRoute
  UserChangePasswordRoute: typeof UserChangePasswordRoute
  UserEmailVerificationRoute: typeof UserEmailVerificationRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserAccountSettingsRoute: UserAccountSettingsRoute,
  UserChangeEmailRoute: UserChangeEmailRoute,
  UserChangePasswordRoute: UserChangePasswordRoute,
  UserEmailVerificationRoute: UserEmailVerificationRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/tenant': typeof TenantRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/example-form': typeof examplesExampleFormRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/user-management': typeof AdminUserManagementRoute
  '/app/communications': typeof AppCommunicationsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/financials': typeof AppFinancialsRouteWithChildren
  '/app/leases': typeof AppLeasesRouteWithChildren
  '/app/maintenance': typeof AppMaintenanceRouteWithChildren
  '/app/pets': typeof AppPetsRoute
  '/app/properties': typeof AppPropertiesRouteWithChildren
  '/app/tenants': typeof AppTenantsRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRouteWithChildren
  '/tenant/dashboard': typeof TenantDashboardRoute
  '/tenant/payments': typeof TenantPaymentsRouteWithChildren
  '/user/account-settings': typeof UserAccountSettingsRoute
  '/user/change-email': typeof UserChangeEmailRoute
  '/user/change-password': typeof UserChangePasswordRoute
  '/user/email-verification': typeof UserEmailVerificationRoute
  '/app/financials/deposits': typeof AppFinancialsDepositsRoute
  '/app/financials/expenses': typeof AppFinancialsExpensesRoute
  '/app/financials/payments': typeof AppFinancialsPaymentsRoute
  '/app/inspections/$inspectionId': typeof AppInspectionsInspectionIdRoute
  '/app/inspections/new': typeof AppInspectionsNewRoute
  '/app/leases/$leaseId': typeof AppLeasesLeaseIdRoute
  '/app/leases/new': typeof AppLeasesNewRoute
  '/app/leases/templates': typeof AppLeasesTemplatesRoute
  '/app/maintenance/$workOrderId': typeof AppMaintenanceWorkOrderIdRoute
  '/app/maintenance/budgets': typeof AppMaintenanceBudgetsRouteWithChildren
  '/app/maintenance/costs': typeof AppMaintenanceCostsRoute
  '/app/maintenance/schedules': typeof AppMaintenanceSchedulesRouteWithChildren
  '/app/maintenance/vendors': typeof AppMaintenanceVendorsRouteWithChildren
  '/app/move-out/$leaseId': typeof AppMoveOutLeaseIdRoute
  '/app/properties/$propertyId': typeof AppPropertiesPropertyIdRouteWithChildren
  '/app/properties/new': typeof AppPropertiesNewRoute
  '/app/tenants/$tenantId': typeof AppTenantsTenantIdRoute
  '/app/tenants/new': typeof AppTenantsNewRoute
  '/auth/sign-up/profile': typeof AuthSignUpProfileRoute
  '/auth/sign-up/verify': typeof AuthSignUpVerifyRoute
  '/auth/sign-up/welcome': typeof AuthSignUpWelcomeRoute
  '/tenant/payments/cancel': typeof TenantPaymentsCancelRoute
  '/tenant/payments/success': typeof TenantPaymentsSuccessRoute
  '/app/financials/': typeof AppFinancialsIndexRoute
  '/app/inspections': typeof AppInspectionsIndexRoute
  '/app/leases/': typeof AppLeasesIndexRoute
  '/app/maintenance/': typeof AppMaintenanceIndexRoute
  '/app/properties/': typeof AppPropertiesIndexRoute
  '/app/tenants/': typeof AppTenantsIndexRoute
  '/app/maintenance/budgets/$budgetId': typeof AppMaintenanceBudgetsBudgetIdRoute
  '/app/maintenance/budgets/comparison': typeof AppMaintenanceBudgetsComparisonRoute
  '/app/maintenance/schedules/$scheduleId': typeof AppMaintenanceSchedulesScheduleIdRoute
  '/app/maintenance/vendors/$vendorId': typeof AppMaintenanceVendorsVendorIdRoute
  '/app/properties/$propertyId/edit': typeof AppPropertiesPropertyIdEditRoute
  '/app/properties/$propertyId/units': typeof AppPropertiesPropertyIdUnitsRouteWithChildren
  '/app/properties/$propertyId/': typeof AppPropertiesPropertyIdIndexRoute
  '/app/properties/$propertyId/units/new': typeof AppPropertiesPropertyIdUnitsNewRoute
  '/app/properties/$propertyId/units/$unitId/edit': typeof AppPropertiesPropertyIdUnitsUnitIdEditRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/tenant': typeof TenantRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/example-form': typeof examplesExampleFormRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/user-management': typeof AdminUserManagementRoute
  '/app/communications': typeof AppCommunicationsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/pets': typeof AppPetsRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRouteWithChildren
  '/tenant/dashboard': typeof TenantDashboardRoute
  '/tenant/payments': typeof TenantPaymentsRouteWithChildren
  '/user/account-settings': typeof UserAccountSettingsRoute
  '/user/change-email': typeof UserChangeEmailRoute
  '/user/change-password': typeof UserChangePasswordRoute
  '/user/email-verification': typeof UserEmailVerificationRoute
  '/app/financials/deposits': typeof AppFinancialsDepositsRoute
  '/app/financials/expenses': typeof AppFinancialsExpensesRoute
  '/app/financials/payments': typeof AppFinancialsPaymentsRoute
  '/app/inspections/$inspectionId': typeof AppInspectionsInspectionIdRoute
  '/app/inspections/new': typeof AppInspectionsNewRoute
  '/app/leases/$leaseId': typeof AppLeasesLeaseIdRoute
  '/app/leases/new': typeof AppLeasesNewRoute
  '/app/leases/templates': typeof AppLeasesTemplatesRoute
  '/app/maintenance/$workOrderId': typeof AppMaintenanceWorkOrderIdRoute
  '/app/maintenance/budgets': typeof AppMaintenanceBudgetsRouteWithChildren
  '/app/maintenance/costs': typeof AppMaintenanceCostsRoute
  '/app/maintenance/schedules': typeof AppMaintenanceSchedulesRouteWithChildren
  '/app/maintenance/vendors': typeof AppMaintenanceVendorsRouteWithChildren
  '/app/move-out/$leaseId': typeof AppMoveOutLeaseIdRoute
  '/app/properties/new': typeof AppPropertiesNewRoute
  '/app/tenants/$tenantId': typeof AppTenantsTenantIdRoute
  '/app/tenants/new': typeof AppTenantsNewRoute
  '/auth/sign-up/profile': typeof AuthSignUpProfileRoute
  '/auth/sign-up/verify': typeof AuthSignUpVerifyRoute
  '/auth/sign-up/welcome': typeof AuthSignUpWelcomeRoute
  '/tenant/payments/cancel': typeof TenantPaymentsCancelRoute
  '/tenant/payments/success': typeof TenantPaymentsSuccessRoute
  '/app/financials': typeof AppFinancialsIndexRoute
  '/app/inspections': typeof AppInspectionsIndexRoute
  '/app/leases': typeof AppLeasesIndexRoute
  '/app/maintenance': typeof AppMaintenanceIndexRoute
  '/app/properties': typeof AppPropertiesIndexRoute
  '/app/tenants': typeof AppTenantsIndexRoute
  '/app/maintenance/budgets/$budgetId': typeof AppMaintenanceBudgetsBudgetIdRoute
  '/app/maintenance/budgets/comparison': typeof AppMaintenanceBudgetsComparisonRoute
  '/app/maintenance/schedules/$scheduleId': typeof AppMaintenanceSchedulesScheduleIdRoute
  '/app/maintenance/vendors/$vendorId': typeof AppMaintenanceVendorsVendorIdRoute
  '/app/properties/$propertyId/edit': typeof AppPropertiesPropertyIdEditRoute
  '/app/properties/$propertyId/units': typeof AppPropertiesPropertyIdUnitsRouteWithChildren
  '/app/properties/$propertyId': typeof AppPropertiesPropertyIdIndexRoute
  '/app/properties/$propertyId/units/new': typeof AppPropertiesPropertyIdUnitsNewRoute
  '/app/properties/$propertyId/units/$unitId/edit': typeof AppPropertiesPropertyIdUnitsUnitIdEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/tenant': typeof TenantRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/(examples)/example-form': typeof examplesExampleFormRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/user-management': typeof AdminUserManagementRoute
  '/app/communications': typeof AppCommunicationsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/financials': typeof AppFinancialsRouteWithChildren
  '/app/leases': typeof AppLeasesRouteWithChildren
  '/app/maintenance': typeof AppMaintenanceRouteWithChildren
  '/app/pets': typeof AppPetsRoute
  '/app/properties': typeof AppPropertiesRouteWithChildren
  '/app/tenants': typeof AppTenantsRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRouteWithChildren
  '/tenant/dashboard': typeof TenantDashboardRoute
  '/tenant/payments': typeof TenantPaymentsRouteWithChildren
  '/user/account-settings': typeof UserAccountSettingsRoute
  '/user/change-email': typeof UserChangeEmailRoute
  '/user/change-password': typeof UserChangePasswordRoute
  '/user/email-verification': typeof UserEmailVerificationRoute
  '/app/financials/deposits': typeof AppFinancialsDepositsRoute
  '/app/financials/expenses': typeof AppFinancialsExpensesRoute
  '/app/financials/payments': typeof AppFinancialsPaymentsRoute
  '/app/inspections/$inspectionId': typeof AppInspectionsInspectionIdRoute
  '/app/inspections/new': typeof AppInspectionsNewRoute
  '/app/leases/$leaseId': typeof AppLeasesLeaseIdRoute
  '/app/leases/new': typeof AppLeasesNewRoute
  '/app/leases/templates': typeof AppLeasesTemplatesRoute
  '/app/maintenance/$workOrderId': typeof AppMaintenanceWorkOrderIdRoute
  '/app/maintenance/budgets': typeof AppMaintenanceBudgetsRouteWithChildren
  '/app/maintenance/costs': typeof AppMaintenanceCostsRoute
  '/app/maintenance/schedules': typeof AppMaintenanceSchedulesRouteWithChildren
  '/app/maintenance/vendors': typeof AppMaintenanceVendorsRouteWithChildren
  '/app/move-out/$leaseId': typeof AppMoveOutLeaseIdRoute
  '/app/properties/$propertyId': typeof AppPropertiesPropertyIdRouteWithChildren
  '/app/properties/new': typeof AppPropertiesNewRoute
  '/app/tenants/$tenantId': typeof AppTenantsTenantIdRoute
  '/app/tenants/new': typeof AppTenantsNewRoute
  '/auth/sign-up/profile': typeof AuthSignUpProfileRoute
  '/auth/sign-up/verify': typeof AuthSignUpVerifyRoute
  '/auth/sign-up/welcome': typeof AuthSignUpWelcomeRoute
  '/tenant/payments/cancel': typeof TenantPaymentsCancelRoute
  '/tenant/payments/success': typeof TenantPaymentsSuccessRoute
  '/app/financials/': typeof AppFinancialsIndexRoute
  '/app/inspections/': typeof AppInspectionsIndexRoute
  '/app/leases/': typeof AppLeasesIndexRoute
  '/app/maintenance/': typeof AppMaintenanceIndexRoute
  '/app/properties/': typeof AppPropertiesIndexRoute
  '/app/tenants/': typeof AppTenantsIndexRoute
  '/app/maintenance/budgets/$budgetId': typeof AppMaintenanceBudgetsBudgetIdRoute
  '/app/maintenance/budgets/comparison': typeof AppMaintenanceBudgetsComparisonRoute
  '/app/maintenance/schedules/$scheduleId': typeof AppMaintenanceSchedulesScheduleIdRoute
  '/app/maintenance/vendors/$vendorId': typeof AppMaintenanceVendorsVendorIdRoute
  '/app/properties/$propertyId/edit': typeof AppPropertiesPropertyIdEditRoute
  '/app/properties/$propertyId/units': typeof AppPropertiesPropertyIdUnitsRouteWithChildren
  '/app/properties/$propertyId/': typeof AppPropertiesPropertyIdIndexRoute
  '/app/properties/$propertyId/units/new': typeof AppPropertiesPropertyIdUnitsNewRoute
  '/app/properties/$propertyId/units/$unitId/edit': typeof AppPropertiesPropertyIdUnitsUnitIdEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/tenant'
    | '/user'
    | '/example-form'
    | '/admin/dashboard'
    | '/admin/user-management'
    | '/app/communications'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/financials'
    | '/app/leases'
    | '/app/maintenance'
    | '/app/pets'
    | '/app/properties'
    | '/app/tenants'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/tenant/dashboard'
    | '/tenant/payments'
    | '/user/account-settings'
    | '/user/change-email'
    | '/user/change-password'
    | '/user/email-verification'
    | '/app/financials/deposits'
    | '/app/financials/expenses'
    | '/app/financials/payments'
    | '/app/inspections/$inspectionId'
    | '/app/inspections/new'
    | '/app/leases/$leaseId'
    | '/app/leases/new'
    | '/app/leases/templates'
    | '/app/maintenance/$workOrderId'
    | '/app/maintenance/budgets'
    | '/app/maintenance/costs'
    | '/app/maintenance/schedules'
    | '/app/maintenance/vendors'
    | '/app/move-out/$leaseId'
    | '/app/properties/$propertyId'
    | '/app/properties/new'
    | '/app/tenants/$tenantId'
    | '/app/tenants/new'
    | '/auth/sign-up/profile'
    | '/auth/sign-up/verify'
    | '/auth/sign-up/welcome'
    | '/tenant/payments/cancel'
    | '/tenant/payments/success'
    | '/app/financials/'
    | '/app/inspections'
    | '/app/leases/'
    | '/app/maintenance/'
    | '/app/properties/'
    | '/app/tenants/'
    | '/app/maintenance/budgets/$budgetId'
    | '/app/maintenance/budgets/comparison'
    | '/app/maintenance/schedules/$scheduleId'
    | '/app/maintenance/vendors/$vendorId'
    | '/app/properties/$propertyId/edit'
    | '/app/properties/$propertyId/units'
    | '/app/properties/$propertyId/'
    | '/app/properties/$propertyId/units/new'
    | '/app/properties/$propertyId/units/$unitId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/tenant'
    | '/user'
    | '/example-form'
    | '/admin/dashboard'
    | '/admin/user-management'
    | '/app/communications'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/pets'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/tenant/dashboard'
    | '/tenant/payments'
    | '/user/account-settings'
    | '/user/change-email'
    | '/user/change-password'
    | '/user/email-verification'
    | '/app/financials/deposits'
    | '/app/financials/expenses'
    | '/app/financials/payments'
    | '/app/inspections/$inspectionId'
    | '/app/inspections/new'
    | '/app/leases/$leaseId'
    | '/app/leases/new'
    | '/app/leases/templates'
    | '/app/maintenance/$workOrderId'
    | '/app/maintenance/budgets'
    | '/app/maintenance/costs'
    | '/app/maintenance/schedules'
    | '/app/maintenance/vendors'
    | '/app/move-out/$leaseId'
    | '/app/properties/new'
    | '/app/tenants/$tenantId'
    | '/app/tenants/new'
    | '/auth/sign-up/profile'
    | '/auth/sign-up/verify'
    | '/auth/sign-up/welcome'
    | '/tenant/payments/cancel'
    | '/tenant/payments/success'
    | '/app/financials'
    | '/app/inspections'
    | '/app/leases'
    | '/app/maintenance'
    | '/app/properties'
    | '/app/tenants'
    | '/app/maintenance/budgets/$budgetId'
    | '/app/maintenance/budgets/comparison'
    | '/app/maintenance/schedules/$scheduleId'
    | '/app/maintenance/vendors/$vendorId'
    | '/app/properties/$propertyId/edit'
    | '/app/properties/$propertyId/units'
    | '/app/properties/$propertyId'
    | '/app/properties/$propertyId/units/new'
    | '/app/properties/$propertyId/units/$unitId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/tenant'
    | '/user'
    | '/(examples)/example-form'
    | '/admin/dashboard'
    | '/admin/user-management'
    | '/app/communications'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/financials'
    | '/app/leases'
    | '/app/maintenance'
    | '/app/pets'
    | '/app/properties'
    | '/app/tenants'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/tenant/dashboard'
    | '/tenant/payments'
    | '/user/account-settings'
    | '/user/change-email'
    | '/user/change-password'
    | '/user/email-verification'
    | '/app/financials/deposits'
    | '/app/financials/expenses'
    | '/app/financials/payments'
    | '/app/inspections/$inspectionId'
    | '/app/inspections/new'
    | '/app/leases/$leaseId'
    | '/app/leases/new'
    | '/app/leases/templates'
    | '/app/maintenance/$workOrderId'
    | '/app/maintenance/budgets'
    | '/app/maintenance/costs'
    | '/app/maintenance/schedules'
    | '/app/maintenance/vendors'
    | '/app/move-out/$leaseId'
    | '/app/properties/$propertyId'
    | '/app/properties/new'
    | '/app/tenants/$tenantId'
    | '/app/tenants/new'
    | '/auth/sign-up/profile'
    | '/auth/sign-up/verify'
    | '/auth/sign-up/welcome'
    | '/tenant/payments/cancel'
    | '/tenant/payments/success'
    | '/app/financials/'
    | '/app/inspections/'
    | '/app/leases/'
    | '/app/maintenance/'
    | '/app/properties/'
    | '/app/tenants/'
    | '/app/maintenance/budgets/$budgetId'
    | '/app/maintenance/budgets/comparison'
    | '/app/maintenance/schedules/$scheduleId'
    | '/app/maintenance/vendors/$vendorId'
    | '/app/properties/$propertyId/edit'
    | '/app/properties/$propertyId/units'
    | '/app/properties/$propertyId/'
    | '/app/properties/$propertyId/units/new'
    | '/app/properties/$propertyId/units/$unitId/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  TenantRoute: typeof TenantRouteWithChildren
  UserRoute: typeof UserRouteWithChildren
  examplesExampleFormRoute: typeof examplesExampleFormRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  TenantRoute: TenantRouteWithChildren,
  UserRoute: UserRouteWithChildren,
  examplesExampleFormRoute: examplesExampleFormRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/app",
        "/auth",
        "/tenant",
        "/user",
        "/(examples)/example-form"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin.tsx",
      "children": [
        "/admin/dashboard",
        "/admin/user-management"
      ]
    },
    "/app": {
      "filePath": "app.tsx",
      "children": [
        "/app/communications",
        "/app/dashboard",
        "/app/documents",
        "/app/financials",
        "/app/leases",
        "/app/maintenance",
        "/app/pets",
        "/app/properties",
        "/app/tenants",
        "/app/inspections/$inspectionId",
        "/app/inspections/new",
        "/app/move-out/$leaseId",
        "/app/inspections/"
      ]
    },
    "/auth": {
      "filePath": "auth.tsx",
      "children": [
        "/auth/sign-in",
        "/auth/sign-up"
      ]
    },
    "/tenant": {
      "filePath": "tenant.tsx",
      "children": [
        "/tenant/dashboard",
        "/tenant/payments"
      ]
    },
    "/user": {
      "filePath": "user.tsx",
      "children": [
        "/user/account-settings",
        "/user/change-email",
        "/user/change-password",
        "/user/email-verification"
      ]
    },
    "/(examples)/example-form": {
      "filePath": "(examples)/example-form.tsx"
    },
    "/admin/dashboard": {
      "filePath": "admin.dashboard.tsx",
      "parent": "/admin"
    },
    "/admin/user-management": {
      "filePath": "admin.user-management.tsx",
      "parent": "/admin"
    },
    "/app/communications": {
      "filePath": "app.communications.tsx",
      "parent": "/app"
    },
    "/app/dashboard": {
      "filePath": "app.dashboard.tsx",
      "parent": "/app"
    },
    "/app/documents": {
      "filePath": "app.documents.tsx",
      "parent": "/app"
    },
    "/app/financials": {
      "filePath": "app.financials.tsx",
      "parent": "/app",
      "children": [
        "/app/financials/deposits",
        "/app/financials/expenses",
        "/app/financials/payments",
        "/app/financials/"
      ]
    },
    "/app/leases": {
      "filePath": "app.leases.tsx",
      "parent": "/app",
      "children": [
        "/app/leases/$leaseId",
        "/app/leases/new",
        "/app/leases/templates",
        "/app/leases/"
      ]
    },
    "/app/maintenance": {
      "filePath": "app.maintenance.tsx",
      "parent": "/app",
      "children": [
        "/app/maintenance/$workOrderId",
        "/app/maintenance/budgets",
        "/app/maintenance/costs",
        "/app/maintenance/schedules",
        "/app/maintenance/vendors",
        "/app/maintenance/"
      ]
    },
    "/app/pets": {
      "filePath": "app.pets.tsx",
      "parent": "/app"
    },
    "/app/properties": {
      "filePath": "app.properties.tsx",
      "parent": "/app",
      "children": [
        "/app/properties/$propertyId",
        "/app/properties/new",
        "/app/properties/"
      ]
    },
    "/app/tenants": {
      "filePath": "app.tenants.tsx",
      "parent": "/app",
      "children": [
        "/app/tenants/$tenantId",
        "/app/tenants/new",
        "/app/tenants/"
      ]
    },
    "/auth/sign-in": {
      "filePath": "auth.sign-in.tsx",
      "parent": "/auth"
    },
    "/auth/sign-up": {
      "filePath": "auth.sign-up.tsx",
      "parent": "/auth",
      "children": [
        "/auth/sign-up/profile",
        "/auth/sign-up/verify",
        "/auth/sign-up/welcome"
      ]
    },
    "/tenant/dashboard": {
      "filePath": "tenant.dashboard.tsx",
      "parent": "/tenant"
    },
    "/tenant/payments": {
      "filePath": "tenant.payments.tsx",
      "parent": "/tenant",
      "children": [
        "/tenant/payments/cancel",
        "/tenant/payments/success"
      ]
    },
    "/user/account-settings": {
      "filePath": "user.account-settings.tsx",
      "parent": "/user"
    },
    "/user/change-email": {
      "filePath": "user.change-email.tsx",
      "parent": "/user"
    },
    "/user/change-password": {
      "filePath": "user.change-password.tsx",
      "parent": "/user"
    },
    "/user/email-verification": {
      "filePath": "user.email-verification.tsx",
      "parent": "/user"
    },
    "/app/financials/deposits": {
      "filePath": "app.financials.deposits.tsx",
      "parent": "/app/financials"
    },
    "/app/financials/expenses": {
      "filePath": "app.financials.expenses.tsx",
      "parent": "/app/financials"
    },
    "/app/financials/payments": {
      "filePath": "app.financials.payments.tsx",
      "parent": "/app/financials"
    },
    "/app/inspections/$inspectionId": {
      "filePath": "app.inspections.$inspectionId.tsx",
      "parent": "/app"
    },
    "/app/inspections/new": {
      "filePath": "app.inspections.new.tsx",
      "parent": "/app"
    },
    "/app/leases/$leaseId": {
      "filePath": "app.leases.$leaseId.tsx",
      "parent": "/app/leases"
    },
    "/app/leases/new": {
      "filePath": "app.leases.new.tsx",
      "parent": "/app/leases"
    },
    "/app/leases/templates": {
      "filePath": "app.leases.templates.tsx",
      "parent": "/app/leases"
    },
    "/app/maintenance/$workOrderId": {
      "filePath": "app.maintenance.$workOrderId.tsx",
      "parent": "/app/maintenance"
    },
    "/app/maintenance/budgets": {
      "filePath": "app.maintenance.budgets.tsx",
      "parent": "/app/maintenance",
      "children": [
        "/app/maintenance/budgets/$budgetId",
        "/app/maintenance/budgets/comparison"
      ]
    },
    "/app/maintenance/costs": {
      "filePath": "app.maintenance.costs.tsx",
      "parent": "/app/maintenance"
    },
    "/app/maintenance/schedules": {
      "filePath": "app.maintenance.schedules.tsx",
      "parent": "/app/maintenance",
      "children": [
        "/app/maintenance/schedules/$scheduleId"
      ]
    },
    "/app/maintenance/vendors": {
      "filePath": "app.maintenance.vendors.tsx",
      "parent": "/app/maintenance",
      "children": [
        "/app/maintenance/vendors/$vendorId"
      ]
    },
    "/app/move-out/$leaseId": {
      "filePath": "app.move-out.$leaseId.tsx",
      "parent": "/app"
    },
    "/app/properties/$propertyId": {
      "filePath": "app.properties.$propertyId.tsx",
      "parent": "/app/properties",
      "children": [
        "/app/properties/$propertyId/edit",
        "/app/properties/$propertyId/units",
        "/app/properties/$propertyId/"
      ]
    },
    "/app/properties/new": {
      "filePath": "app.properties.new.tsx",
      "parent": "/app/properties"
    },
    "/app/tenants/$tenantId": {
      "filePath": "app.tenants.$tenantId.tsx",
      "parent": "/app/tenants"
    },
    "/app/tenants/new": {
      "filePath": "app.tenants.new.tsx",
      "parent": "/app/tenants"
    },
    "/auth/sign-up/profile": {
      "filePath": "auth.sign-up.profile.tsx",
      "parent": "/auth/sign-up"
    },
    "/auth/sign-up/verify": {
      "filePath": "auth.sign-up.verify.tsx",
      "parent": "/auth/sign-up"
    },
    "/auth/sign-up/welcome": {
      "filePath": "auth.sign-up.welcome.tsx",
      "parent": "/auth/sign-up"
    },
    "/tenant/payments/cancel": {
      "filePath": "tenant.payments.cancel.tsx",
      "parent": "/tenant/payments"
    },
    "/tenant/payments/success": {
      "filePath": "tenant.payments.success.tsx",
      "parent": "/tenant/payments"
    },
    "/app/financials/": {
      "filePath": "app.financials.index.tsx",
      "parent": "/app/financials"
    },
    "/app/inspections/": {
      "filePath": "app.inspections.index.tsx",
      "parent": "/app"
    },
    "/app/leases/": {
      "filePath": "app.leases.index.tsx",
      "parent": "/app/leases"
    },
    "/app/maintenance/": {
      "filePath": "app.maintenance.index.tsx",
      "parent": "/app/maintenance"
    },
    "/app/properties/": {
      "filePath": "app.properties.index.tsx",
      "parent": "/app/properties"
    },
    "/app/tenants/": {
      "filePath": "app.tenants.index.tsx",
      "parent": "/app/tenants"
    },
    "/app/maintenance/budgets/$budgetId": {
      "filePath": "app.maintenance.budgets.$budgetId.tsx",
      "parent": "/app/maintenance/budgets"
    },
    "/app/maintenance/budgets/comparison": {
      "filePath": "app.maintenance.budgets.comparison.tsx",
      "parent": "/app/maintenance/budgets"
    },
    "/app/maintenance/schedules/$scheduleId": {
      "filePath": "app.maintenance.schedules.$scheduleId.tsx",
      "parent": "/app/maintenance/schedules"
    },
    "/app/maintenance/vendors/$vendorId": {
      "filePath": "app.maintenance.vendors.$vendorId.tsx",
      "parent": "/app/maintenance/vendors"
    },
    "/app/properties/$propertyId/edit": {
      "filePath": "app.properties.$propertyId.edit.tsx",
      "parent": "/app/properties/$propertyId"
    },
    "/app/properties/$propertyId/units": {
      "filePath": "app.properties.$propertyId.units.tsx",
      "parent": "/app/properties/$propertyId",
      "children": [
        "/app/properties/$propertyId/units/new",
        "/app/properties/$propertyId/units/$unitId/edit"
      ]
    },
    "/app/properties/$propertyId/": {
      "filePath": "app.properties.$propertyId.index.tsx",
      "parent": "/app/properties/$propertyId"
    },
    "/app/properties/$propertyId/units/new": {
      "filePath": "app.properties.$propertyId.units.new.tsx",
      "parent": "/app/properties/$propertyId/units"
    },
    "/app/properties/$propertyId/units/$unitId/edit": {
      "filePath": "app.properties.$propertyId.units.$unitId.edit.tsx",
      "parent": "/app/properties/$propertyId/units"
    }
  }
}
ROUTE_MANIFEST_END */
